//
//  DisclaimersView.swift
//  ios
//
//  Screen: Legal disclaimers — AI, financial, and general app disclaimers
//  Required for financial and AI applications
//

import SwiftUI

struct DisclaimersView: View {
    var body: some View {
        ZStack {
            AppColors.background
                .ignoresSafeArea()

            ScrollView(showsIndicators: false) {
                LazyVStack(spacing: AppSpacing.xxl) {
                    // AI Disclaimer
                    DisclaimerCard(
                        icon: "brain.head.profile",
                        iconColor: AppColors.textSecondary,
                        title: "AI-Generated Content",
                        items: [
                            "All analysis, reports, and insights are generated by artificial intelligence models and should be treated as informational tools, not professional advice.",
                            "AI models can produce inaccurate, incomplete, or outdated information. Always verify critical data from primary sources.",
                            "The AI personas (Buffett, Lynch, etc.) are educational simulations and do not represent the actual views of these investors.",
                            "Model outputs may change over time as AI systems are updated and improved."
                        ]
                    )

                    // Financial Disclaimer
                    DisclaimerCard(
                        icon: "dollarsign.circle",
                        iconColor: AppColors.textSecondary,
                        title: "Financial Disclaimer",
                        items: [
                            "Nothing in this app constitutes financial, investment, legal, or tax advice. All content is for informational and educational purposes only.",
                            "Past performance does not guarantee future results. All investments carry risk, including the potential loss of principal.",
                            "You should consult a qualified financial advisor before making any investment decisions.",
                            "Caydex and its operators are not registered investment advisors, broker-dealers, or financial planners."
                        ]
                    )

                    // Data Disclaimer
                    DisclaimerCard(
                        icon: "server.rack",
                        iconColor: AppColors.textSecondary,
                        title: "Data Accuracy",
                        items: [
                            "Market data, financial statements, and pricing information are sourced from third-party providers and may be delayed or inaccurate.",
                            "Real-time quotes may be delayed by 15-20 minutes depending on the exchange and data provider.",
                            "We make reasonable efforts to ensure accuracy but cannot guarantee the completeness or timeliness of all data.",
                            "Discrepancies between app data and official exchange data should be resolved in favor of the official source."
                        ]
                    )

                    // No Guarantee
                    DisclaimerCard(
                        icon: "shield.slash",
                        iconColor: AppColors.textSecondary,
                        title: "No Guarantees",
                        items: [
                            "This application is provided \"as is\" without warranties of any kind, express or implied.",
                            "We do not guarantee uninterrupted service, error-free operation, or that the app will meet your specific requirements.",
                            "Credit purchases are non-refundable except as required by applicable law.",
                            "We reserve the right to modify, suspend, or discontinue features at any time."
                        ]
                    )

                    // User Responsibility
                    DisclaimerCard(
                        icon: "person.badge.shield.checkmark",
                        iconColor: AppColors.textSecondary,
                        title: "Your Responsibility",
                        items: [
                            "You are solely responsible for your investment decisions and their outcomes.",
                            "You agree to use this app in compliance with all applicable laws and regulations in your jurisdiction.",
                            "You acknowledge that securities trading involves substantial risk and may not be suitable for all investors."
                        ]
                    )

                    Spacer()
                        .frame(height: AppSpacing.xxxl)
                }
                .padding(.top, AppSpacing.md)
            }
        }
        .navigationTitle("Disclaimers")
        .navigationBarTitleDisplayMode(.inline)
        .toolbarBackground(AppColors.background, for: .navigationBar)
        .toolbarBackground(.visible, for: .navigationBar)
    }
}

// MARK: - Disclaimer Card

struct DisclaimerCard: View {
    let icon: String
    let iconColor: Color
    let title: String
    let items: [String]

    var body: some View {
        VStack(alignment: .leading, spacing: AppSpacing.md) {
            // Header
            HStack(spacing: AppSpacing.md) {
                Image(systemName: icon)
                    .font(AppTypography.iconLarge)
                    .foregroundColor(iconColor)
                    .frame(width: 40, height: 40)

                Text(title)
                    .font(AppTypography.bodyEmphasis)
                    .foregroundColor(AppColors.textPrimary)
            }

            // Items
            VStack(alignment: .leading, spacing: AppSpacing.sm) {
                ForEach(items, id: \.self) { item in
                    HStack(alignment: .top, spacing: AppSpacing.sm) {
                        Circle()
                            .fill(AppColors.textMuted)
                            .frame(width: 5, height: 5)
                            .padding(.top, 6)

                        Text(item)
                            .font(AppTypography.bodySmall)
                            .foregroundColor(AppColors.textSecondary)
                            .fixedSize(horizontal: false, vertical: true)
                    }
                }
            }
        }
        .padding(AppSpacing.lg)
        .background(
            RoundedRectangle(cornerRadius: AppCornerRadius.large)
                .fill(AppColors.cardBackground)
        )
        .padding(.horizontal, AppSpacing.lg)
    }
}

// MARK: - Preview

#Preview {
    NavigationStack {
        DisclaimersView()
    }
    .preferredColorScheme(.dark)
}
