"""
POC: render the detailed-analysis PDF page 1 from a realistic sample report.

Network-free. Writes an HTML file; convert to PDF with headless Chrome (the
production path uses WeasyPrint, but Chrome lets us preview without the native
libs). Run:

    ./backend/venv/bin/python backend/scripts/render_pdf_poc.py
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))  # backend/

from app.services.pdf_report_service import build_context, render_html  # noqa: E402

# Plausible 13-point trailing-12M monthly close series for ORCL.
_PRICES = [118.4, 124.1, 121.0, 133.7, 142.9, 138.2, 151.5, 149.0,
           158.8, 164.3, 160.1, 169.7, 172.4]

SAMPLE = {
    "symbol": "ORCL",
    "company_name": "Oracle Corporation",
    "exchange": "NYSE",
    "sector": "Technology · Software—Infrastructure",
    "live_date": "Jun 13, 2026",
    "agent": {"name": "Warren Buffett", "tagline": "Value Lens"},
    "quality_score": 72,
    "quality_label": "Fair Quality Business",
    "core_thesis": {
        "bull_case": [
            "OCI revenue compounding >50% with a multi-year RPO backlog that locks in "
            "revenue visibility well into the decade.",
            "Mission-critical database and ERP suites create deep switching costs and "
            "durable pricing power.",
            "Operating margins expand as cloud scales; disciplined buybacks steadily "
            "shrink the share count.",
        ],
        "bear_case": [
            "Net leverage stays elevated versus hyperscaler peers, limiting balance-"
            "sheet flexibility.",
            "Valuation already prices in near-flawless cloud execution — little room "
            "for a stumble.",
            "Heavy data-center capex pressures near-term free cash flow conversion.",
        ],
    },
    "fair_value_estimate": 196.0,
    "_scoring_inputs": {
        "profitability": 84,
        "health": 58,
        "growth": 76,
        "valuation": 47,
        "insider": 52,
        "macro": 63,
        "analyst": 81,
        "momentum": 89,
    },
    "price_action": {
        "current_price": 172.40,
        "prices": _PRICES,
        "change_pct": 41.2,
        "window_label": "12M",
    },
    "wall_street_consensus": {
        "target_price": 205.0,
        "low_target": 150.0,
        "high_target": 260.0,
        "analyst_strong_buy": 8,
        "analyst_buy": 22,
        "analyst_hold": 12,
        "analyst_sell": 2,
        "analyst_strong_sell": 1,
    },
    "moat_competition": {
        "dimensions": [
            {"name": "Switching", "score": 88, "peer_score": 70},
            {"name": "Brand", "score": 64, "peer_score": 72},
            {"name": "Network", "score": 55, "peer_score": 60},
            {"name": "Cost Adv.", "score": 60, "peer_score": 65},
            {"name": "Scale", "score": 82, "peer_score": 78},
            {"name": "Intangibles", "score": 79, "peer_score": 68},
        ],
    },
    "executive_summary_text": (
        "Oracle has transformed from a legacy database vendor into a credible "
        "hyperscale cloud contender, with OCI and a fast-growing RPO backlog "
        "underwriting multi-year revenue visibility. Through a value lens it screens "
        "as a fair-quality compounder — deep switching costs and scale support durable "
        "margins, while elevated leverage and a full valuation temper the margin of safety."
    ),
    "disclaimer_text": (
        "Generated by Cay AI for informational purposes only. Not investment advice. "
        "Figures reflect a point-in-time snapshot at report date."
    ),
}


def main() -> None:
    ctx = build_context(SAMPLE, fair_value_estimate=SAMPLE["fair_value_estimate"])
    html = render_html(ctx)
    out = Path(__file__).resolve().parent / "poc_output.html"
    out.write_text(html, encoding="utf-8")
    print(f"HTML written: {out}")
    print(f"chars: {len(html)}  | charts present: "
          f"{ {k: bool(v) for k, v in ctx['charts'].items()} }")


if __name__ == "__main__":
    main()
