"""The privileged schema dump must show EVERY public table granted to service_role, and no
client grant that nobody has defended.

WHY THIS FILE EXISTS
--------------------
`test_table_grants_service_role_only.py` replays GRANT/REVOKE statements across the migration
folder. That catches a migration that opens a door — but it is blind to two things that both
happened:

  * A table that no migration ever granted. `daily_briefings`, `market_insights` and
    `social_mentions_history` were created in Supabase Studio; migration 078 REVOKEd the
    clients and wrote a `service_role` POLICY, but never a service_role GRANT. Postgres checks
    the table privilege BEFORE row-level security, and this project carries no
    `ALTER DEFAULT PRIVILEGES … IN SCHEMA public`, so an ungranted table is owner-only. The
    replay was green; production answered `permission denied for table
    social_mentions_history (42501)` on every read (Railway, 2026-09-11). Migration 169 fixes it.
  * A grant made outside the migration flow. `ticker_news_cache` (FMP-licensed news) carried
    `GRANT SELECT TO anon, authenticated` from the default-privilege era; no migration mentions
    it, so no replay could.

`backend/scripts/dump_schema.sh` has dumped WITH privileges since 2026-09-11, which makes the
snapshot the only committed record of the ACL layer. This file reads it — read-only; the
snapshot is regenerated by the dump script, never edited by hand.

WHAT IT ASSERTS
---------------
1. Every `CREATE TABLE public.X` ends with service_role holding SELECT, INSERT, UPDATE and
   DELETE (the backend is the only reader/writer; a partial grant is a latent 42501 on the
   next retention sweep). Views need SELECT.
2. Every table that grants anon or authenticated anything is in `_CLIENT_ACCESS_BY_DESIGN`
   (the same dict the replay test defends), and every entry in that dict is really granted —
   a stale entry is a door nobody is watching either.
3. Every `CREATE SEQUENCE public.*` grants USAGE to service_role (an INSERT into a serial
   table fails without it — see the RAG chunk tables' history).
4. No default privilege in schema public reaches anon/authenticated.

A MIGRATION THAT IS WRITTEN BUT NOT YET APPLIED / RE-DUMPED
-----------------------------------------------------------
The dump lags the folder by design (the user applies migrations by hand, then re-dumps). A
table is tolerated in the `_PENDING_*` dicts below ONLY while (a) the named migration file
really contains the fixing statement and (b) the snapshot still shows the defect. Once the
re-dumped snapshot shows the fix, the entry FAILS this file until it is deleted — an expected-
red pin, not an allow-list. If the re-dump still shows the defect, the file fails for the real
reason.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

from test_table_grants_service_role_only import (
    _CLIENT_ACCESS_BY_DESIGN,
    _MIGRATIONS,
    _strip_sql_comments,
)

_SNAPSHOT = Path(__file__).resolve().parents[1] / "database" / "schema_snapshot.sql"

_FULL = frozenset({"SELECT", "INSERT", "UPDATE", "DELETE"})
_TABLE_ALL = frozenset({"SELECT", "INSERT", "UPDATE", "DELETE", "TRUNCATE", "REFERENCES", "TRIGGER"})
_SEQ_ALL = frozenset({"USAGE", "SELECT", "UPDATE"})
_CLIENT_ROLES = ("anon", "authenticated")

# Tables whose service_role grant is written in a migration the live database has not been
# re-dumped with yet. (table → migration number). Delete the entry once the snapshot shows it.
# 169 (social_mentions_history / daily_briefings / market_insights / three partial caches)
# was applied and the snapshot re-dumped on 2026-09-12 — the entries did their job.
_PENDING_SERVICE_ROLE_GRANTS: dict[str, str] = {}
# Tables whose anon/authenticated grant a not-yet-dumped migration REVOKEs.
# (169: ticker_news_cache / user_settings / device_tokens — landed, see above.)
_PENDING_CLIENT_REVOKES: dict[str, str] = {}

_RE_TABLE = re.compile(r"^CREATE TABLE (?:IF NOT EXISTS )?public\.([a-z0-9_]+)\s*\(", re.M)
_RE_VIEW = re.compile(r"^CREATE (?:OR REPLACE )?VIEW public\.([a-z0-9_]+)\b", re.M)
_RE_SEQ = re.compile(r"^CREATE SEQUENCE (?:IF NOT EXISTS )?public\.([a-z0-9_]+)\b", re.M)
# GRANT ALL ON TABLE public.x TO service_role;
# GRANT SELECT,INSERT,UPDATE ON TABLE public.x TO authenticated;
# REVOKE ALL ON TABLE public.x FROM anon, authenticated;
# GRANT SELECT,USAGE ON SEQUENCE public.x_id_seq TO service_role;
_RE_ACL = re.compile(
    r"^(GRANT|REVOKE)\s+([A-Z_ ,]+?)\s+ON\s+(TABLE|SEQUENCE)\s+public\.([a-z0-9_]+)\s+"
    r"(?:TO|FROM)\s+([^;]+?)(?:\s+WITH\s+GRANT\s+OPTION)?\s*;",
    re.M | re.I,
)
_RE_DEFAULT_PRIV_PUBLIC = re.compile(
    r"^ALTER DEFAULT PRIVILEGES\b[^;]*\bIN SCHEMA public\b[^;]*\bTO\s+([^;]+);", re.M | re.I
)


def _privs(clause: str, kind: str) -> frozenset[str]:
    toks = {t.strip().upper() for t in clause.split(",") if t.strip()}
    if "ALL" in toks or "ALL PRIVILEGES" in toks:
        return _TABLE_ALL if kind == "TABLE" else _SEQ_ALL
    return frozenset(toks)


def _roles(clause: str) -> list[str]:
    return [r.strip().strip('"').lower() for r in clause.split(",") if r.strip()]


def replay(sql: str) -> dict[tuple[str, str, str], set[str]]:
    """{(kind, object, role): effective privileges}, statements applied in file order."""
    state: dict[tuple[str, str, str], set[str]] = {}
    for m in _RE_ACL.finditer(_strip_sql_comments(sql)):
        verb, privs, kind, obj, roles = m.groups()
        kind = kind.upper()
        for role in _roles(roles):
            key = (kind, obj.lower(), role)
            cur = state.setdefault(key, set())
            if verb.upper() == "GRANT":
                cur |= _privs(privs, kind)
            else:
                cur -= _privs(privs, kind)
    return state


def _load() -> tuple[str, dict[tuple[str, str, str], set[str]], list[str], list[str], list[str]]:
    sql = _SNAPSHOT.read_text(encoding="utf-8")
    if not re.search(r"^GRANT .* ON TABLE public\.", sql, re.M):
        pytest.fail(
            f"{_SNAPSHOT.name} carries no table GRANT lines — it was dumped with --no-privileges "
            "(or is the pre-2026-09-11 dump). Re-run backend/scripts/dump_schema.sh; without the "
            "ACL layer this guard proves nothing, so it fails rather than skips."
        )
    return sql, replay(sql), _RE_TABLE.findall(sql), _RE_VIEW.findall(sql), _RE_SEQ.findall(sql)


def _migration(num: str) -> str:
    files = sorted(_MIGRATIONS.glob(f"{num}_*.sql"))
    assert len(files) == 1, f"expected exactly one migration numbered {num}, found {files}"
    return _strip_sql_comments(files[0].read_text(encoding="utf-8"))


def _client_privs(state, table: str) -> dict[str, set[str]]:
    return {r: state.get(("TABLE", table, r), set()) for r in _CLIENT_ROLES
            if state.get(("TABLE", table, r))}


# ── 1. service_role must be able to read AND write every table ─────────────────────────


def test_every_public_table_is_fully_granted_to_service_role():
    _, state, tables, views, _ = _load()
    missing = {}
    for t in tables:
        have = state.get(("TABLE", t, "service_role"), set())
        if not _FULL <= have:
            missing[t] = sorted(have)
    pending_ok, stale = {}, []
    for t, mig in _PENDING_SERVICE_ROLE_GRANTS.items():
        assert re.search(rf"GRANT\s+ALL\s+ON\s+public\.{t}\s+TO\s+service_role", _migration(mig), re.I), \
            f"_PENDING_SERVICE_ROLE_GRANTS names migration {mig} for {t}, but it does not GRANT ALL on it"
        if t in missing:
            pending_ok[t] = missing.pop(t)
        else:
            stale.append(t)
    assert not stale, (
        "the snapshot already shows the service_role grant for these tables — the pending "
        f"entries have done their job; delete them from _PENDING_SERVICE_ROLE_GRANTS: {stale}"
    )
    assert not missing, (
        "public table(s) without a full service_role grant in the snapshot. With no default "
        "privileges in schema public, a table nobody GRANTed is owner-only and every backend "
        "read/write answers 42501 (this is exactly how social_mentions_history broke):\n"
        + "\n".join(f"  • public.{t}: service_role holds {v or 'nothing'}" for t, v in sorted(missing.items()))
        + "\n\nAdd to a migration:  GRANT ALL ON public.<table> TO service_role;"
    )
    for v in views:
        assert "SELECT" in state.get(("TABLE", v, "service_role"), set()), \
            f"view public.{v} is not readable by service_role"


# ── 2. every client grant is defended, every defence is real ───────────────────────────


def test_every_client_grant_is_defended_or_being_revoked():
    _, state, tables, views, _ = _load()
    granted = {t: _client_privs(state, t) for t in tables + views if _client_privs(state, t)}
    undefended = {t: v for t, v in granted.items()
                  if t not in _CLIENT_ACCESS_BY_DESIGN and t not in _PENDING_CLIENT_REVOKES}
    assert not undefended, (
        "table(s) granted to anon/authenticated in the LIVE snapshot with no reason in "
        "_CLIENT_ACCESS_BY_DESIGN — a grant the migration replay could not see:\n"
        + "\n".join(f"  • public.{t}: " + ", ".join(f"{r}={sorted(p)}" for r, p in v.items())
                    for t, v in sorted(undefended.items()))
        + "\n\nEither REVOKE it in a migration (and list it in _PENDING_CLIENT_REVOKES until the "
        "re-dump) or defend it with a reason."
    )
    stale_pending = []
    for t, mig in _PENDING_CLIENT_REVOKES.items():
        assert re.search(rf"REVOKE\s+ALL\s+ON\s+public\.{t}\s+FROM\s+anon,\s*authenticated", _migration(mig), re.I), \
            f"_PENDING_CLIENT_REVOKES names migration {mig} for {t}, but it does not REVOKE it"
        assert t not in _CLIENT_ACCESS_BY_DESIGN, f"{t} cannot be both pending-revoke and by-design"
        if t not in granted:
            stale_pending.append(t)
    assert not stale_pending, (
        "the snapshot no longer grants these tables to a client role — delete them from "
        f"_PENDING_CLIENT_REVOKES: {stale_pending}"
    )
    stale_defence = [t for t in _CLIENT_ACCESS_BY_DESIGN if t not in granted]
    assert not stale_defence, (
        "_CLIENT_ACCESS_BY_DESIGN defends a grant the snapshot does not carry — a reason with "
        f"nothing behind it: {stale_defence}"
    )


# ── 3. sequences and default privileges ───────────────────────────────────────────────


def test_every_public_sequence_is_usable_by_service_role():
    _, state, _, _, seqs = _load()
    assert len(seqs) >= 15, f"the sequence detector found only {len(seqs)} sequences"
    bad = [s for s in seqs if "USAGE" not in state.get(("SEQUENCE", s, "service_role"), set())]
    assert not bad, (
        "sequence(s) without USAGE for service_role — an INSERT into the owning table fails on "
        f"nextval(): {bad}\n\nAdd:  GRANT USAGE, SELECT ON SEQUENCE public.<seq> TO service_role;"
    )


def test_no_default_privilege_in_schema_public_reaches_a_client_role():
    sql, *_ = _load()
    offenders = [m.group(0) for m in _RE_DEFAULT_PRIV_PUBLIC.finditer(_strip_sql_comments(sql))
                 if any(r in _roles(m.group(1)) for r in _CLIENT_ROLES)]
    assert not offenders, (
        "ALTER DEFAULT PRIVILEGES in schema public would hand every FUTURE table to a client "
        f"role before any migration runs:\n" + "\n".join(f"  • {o}" for o in offenders)
    )


# ── 4. the detectors are not vacuous ──────────────────────────────────────────────────


def test_the_snapshot_detectors_are_not_vacuous():
    sql, state, tables, views, seqs = _load()
    assert len(tables) >= 80, f"only {len(tables)} public tables parsed (93 at the 2026-09-11 dump)"
    assert len(views) >= 1 and "vector_search_stats" in views
    assert sum(1 for l in sql.splitlines() if l.startswith("GRANT ")) >= 400, "fewer than 400 GRANT lines"
    table_acl = {k for k in state if k[0] == "TABLE"}
    assert len(table_acl) >= 90, f"only {len(table_acl)} (table, role) ACL entries replayed"

    # Synthetic discrimination, independent of the live tree.
    st = replay(
        "GRANT ALL ON TABLE public.a TO service_role;\n"
        "GRANT SELECT,INSERT ON TABLE public.a TO anon, authenticated WITH GRANT OPTION;\n"
        "REVOKE ALL ON TABLE public.a FROM anon;\n"
        "-- GRANT ALL ON TABLE public.ghost TO anon;\n"
        "/* GRANT ALL ON TABLE public.ghost2 TO anon; */\n"
        "GRANT ALL ON FUNCTION public.f(x integer) TO anon;\n"
        "GRANT SELECT,USAGE ON SEQUENCE public.a_id_seq TO service_role;\n"
        "GRANT ALL ON TABLE auth.users TO anon;\n"
    )
    assert st[("TABLE", "a", "service_role")] == set(_TABLE_ALL)
    assert st[("TABLE", "a", "authenticated")] == {"SELECT", "INSERT"}, "multi-role lists must split"
    assert st[("TABLE", "a", "anon")] == set(), "a later REVOKE ALL must empty the role's set"
    assert not any(k[1] in ("ghost", "ghost2") for k in st), "commented statements must not count"
    assert not any(k[1] == "f" for k in st), "an ON FUNCTION grant must not read as a table grant"
    assert st[("SEQUENCE", "a_id_seq", "service_role")] == {"SELECT", "USAGE"}
    assert not any(k[1] == "users" for k in st), "non-public schemas are out of scope"

    # A grant-less table in a mini-dump is exactly the shape that shipped; the assertion must
    # see it.
    mini = "CREATE TABLE public.orphan (\n    id uuid\n);\nGRANT ALL ON TABLE public.other TO service_role;\n"
    mini_state = replay(mini)
    assert not (_FULL <= mini_state.get(("TABLE", "orphan", "service_role"), set()))
    assert _RE_TABLE.findall(mini) == ["orphan"]

    # The pending dicts describe DEFECTS, so nothing may be declared both fixed-by-design and pending.
    assert not set(_PENDING_SERVICE_ROLE_GRANTS) & set(_CLIENT_ACCESS_BY_DESIGN)
