//
//  GrowthModels.swift
//  ios
//
//  Data models for the Growth Section in the Financial tab
//

import Foundation
import SwiftUI

// MARK: - Growth Metric Type
enum GrowthMetricType: String, CaseIterable, Identifiable {
    case eps = "EPS"
    case revenue = "Revenue"
    case netIncome = "Net Income"
    case operatingProfit = "Operating Profit"
    case freeCashFlow = "Free Cash Flow"

    var id: String { rawValue }

    var description: String {
        switch self {
        case .eps:
            return "Earnings Per Share measures the company's profit allocated to each outstanding share of common stock."
        case .revenue:
            return "Total income generated from sales of goods or services before any expenses are deducted."
        case .netIncome:
            return "The company's total profit after all expenses, taxes, and costs have been subtracted from revenue."
        case .operatingProfit:
            return "Profit from core business operations, excluding interest and taxes."
        case .freeCashFlow:
            return "Cash generated by operations minus capital expenditures. Shows actual cash available to shareholders."
        }
    }
}

// MARK: - Growth Period Type
enum GrowthPeriodType: String, CaseIterable, Identifiable {
    case annual = "Annual"
    case quarterly = "Quarterly"

    var id: String { rawValue }
}

// MARK: - Growth Data Point
struct GrowthDataPoint: Identifiable {
    let id = UUID()
    let period: String              // e.g., "2020", "2021" or "Q1 '24"
    let value: Double               // Absolute value (e.g., 100B)
    let yoyChangePercent: Double    // Year-over-Year change percentage
    let sectorAverageYoY: Double    // Sector average YoY for comparison

    var isPositiveYoY: Bool {
        yoyChangePercent >= 0
    }

    var formattedYoY: String {
        String(format: "%.2f%%", yoyChangePercent)
    }

    var yoyColor: Color {
        yoyChangePercent >= 0 ? AppColors.bullish : AppColors.bearish
    }

    var formattedValue: String {
        formatLargeNumber(value)
    }

    private func formatLargeNumber(_ number: Double) -> String {
        let absNumber = abs(number)
        if absNumber >= 1_000_000_000_000 {
            return String(format: "%.1fT", number / 1_000_000_000_000)
        } else if absNumber >= 1_000_000_000 {
            return String(format: "%.1fB", number / 1_000_000_000)
        } else if absNumber >= 1_000_000 {
            return String(format: "%.1fM", number / 1_000_000)
        } else if absNumber >= 1_000 {
            return String(format: "%.1fK", number / 1_000)
        }
        return String(format: "%.2f", number)
    }
}

// MARK: - Growth Chart Data
struct GrowthChartData {
    let metricType: GrowthMetricType
    let periodType: GrowthPeriodType
    let dataPoints: [GrowthDataPoint]

    var maxValue: Double {
        dataPoints.map { $0.value }.max() ?? 0
    }

    var minValue: Double {
        min(dataPoints.map { $0.value }.min() ?? 0, 0)
    }

    var averageYoY: Double {
        guard !dataPoints.isEmpty else { return 0 }
        return dataPoints.map { $0.yoyChangePercent }.reduce(0, +) / Double(dataPoints.count)
    }

    var formattedAverageYoY: String {
        let sign = averageYoY >= 0 ? "+" : ""
        return "\(sign)\(String(format: "%.1f", averageYoY))%"
    }
}

// MARK: - Growth Section Data
struct GrowthSectionData {
    let epsAnnual: [GrowthDataPoint]
    let epsQuarterly: [GrowthDataPoint]
    let revenueAnnual: [GrowthDataPoint]
    let revenueQuarterly: [GrowthDataPoint]
    let netIncomeAnnual: [GrowthDataPoint]
    let netIncomeQuarterly: [GrowthDataPoint]
    let operatingProfitAnnual: [GrowthDataPoint]
    let operatingProfitQuarterly: [GrowthDataPoint]
    let freeCashFlowAnnual: [GrowthDataPoint]
    let freeCashFlowQuarterly: [GrowthDataPoint]

    func dataPoints(for metric: GrowthMetricType, period: GrowthPeriodType) -> [GrowthDataPoint] {
        switch (metric, period) {
        case (.eps, .annual): return epsAnnual
        case (.eps, .quarterly): return epsQuarterly
        case (.revenue, .annual): return revenueAnnual
        case (.revenue, .quarterly): return revenueQuarterly
        case (.netIncome, .annual): return netIncomeAnnual
        case (.netIncome, .quarterly): return netIncomeQuarterly
        case (.operatingProfit, .annual): return operatingProfitAnnual
        case (.operatingProfit, .quarterly): return operatingProfitQuarterly
        case (.freeCashFlow, .annual): return freeCashFlowAnnual
        case (.freeCashFlow, .quarterly): return freeCashFlowQuarterly
        }
    }

    func chartData(for metric: GrowthMetricType, period: GrowthPeriodType) -> GrowthChartData {
        GrowthChartData(
            metricType: metric,
            periodType: period,
            dataPoints: dataPoints(for: metric, period: period)
        )
    }
}

// MARK: - Sample Data
extension GrowthSectionData {
    static let sampleData = GrowthSectionData(
        epsAnnual: [
            GrowthDataPoint(period: "2020", value: 3.28, yoyChangePercent: 10.78, sectorAverageYoY: 8.5),
            GrowthDataPoint(period: "2021", value: 5.61, yoyChangePercent: 71.04, sectorAverageYoY: 35.2),
            GrowthDataPoint(period: "2022", value: 6.11, yoyChangePercent: 8.91, sectorAverageYoY: 5.8),
            GrowthDataPoint(period: "2023", value: 6.13, yoyChangePercent: 0.33, sectorAverageYoY: -2.1),
            GrowthDataPoint(period: "2024", value: 6.75, yoyChangePercent: 10.11, sectorAverageYoY: 7.5),
            GrowthDataPoint(period: "2025", value: 7.35, yoyChangePercent: 8.89, sectorAverageYoY: 6.2)
        ],
        epsQuarterly: [
            GrowthDataPoint(period: "Q1 '24", value: 1.53, yoyChangePercent: 4.08, sectorAverageYoY: 3.2),
            GrowthDataPoint(period: "Q2 '24", value: 1.40, yoyChangePercent: 11.11, sectorAverageYoY: 8.5),
            GrowthDataPoint(period: "Q3 '24", value: 1.64, yoyChangePercent: 12.33, sectorAverageYoY: 9.1),
            GrowthDataPoint(period: "Q4 '24", value: 2.18, yoyChangePercent: 7.92, sectorAverageYoY: 5.8)
        ],
        revenueAnnual: [
            GrowthDataPoint(period: "2020", value: 86_000_000_000, yoyChangePercent: -2.30, sectorAverageYoY: -5.8),
            GrowthDataPoint(period: "2021", value: 80_000_000_000, yoyChangePercent: -7.42, sectorAverageYoY: 2.5),
            GrowthDataPoint(period: "2022", value: 180_000_000_000, yoyChangePercent: 7.92, sectorAverageYoY: 12.3),
            GrowthDataPoint(period: "2023", value: 220_000_000_000, yoyChangePercent: 5.22, sectorAverageYoY: 15.8),
            GrowthDataPoint(period: "2024", value: 145_000_000_000, yoyChangePercent: -10.92, sectorAverageYoY: -8.2),
            GrowthDataPoint(period: "2025", value: 110_000_000_000, yoyChangePercent: -3.32, sectorAverageYoY: -1.5)
        ],
        revenueQuarterly: [
            GrowthDataPoint(period: "Q1 '24", value: 94_800_000_000, yoyChangePercent: 2.50, sectorAverageYoY: 3.2),
            GrowthDataPoint(period: "Q2 '24", value: 98_200_000_000, yoyChangePercent: 3.40, sectorAverageYoY: 4.5),
            GrowthDataPoint(period: "Q3 '24", value: 89_500_000_000, yoyChangePercent: -1.60, sectorAverageYoY: -0.8),
            GrowthDataPoint(period: "Q4 '24", value: 102_300_000_000, yoyChangePercent: 5.80, sectorAverageYoY: 4.2)
        ],
        netIncomeAnnual: [
            GrowthDataPoint(period: "2020", value: 57_410_000_000, yoyChangePercent: 3.90, sectorAverageYoY: 2.1),
            GrowthDataPoint(period: "2021", value: 94_680_000_000, yoyChangePercent: 64.92, sectorAverageYoY: 45.3),
            GrowthDataPoint(period: "2022", value: 99_800_000_000, yoyChangePercent: 5.41, sectorAverageYoY: 3.8),
            GrowthDataPoint(period: "2023", value: 96_995_000_000, yoyChangePercent: -2.81, sectorAverageYoY: -4.2),
            GrowthDataPoint(period: "2024", value: 105_000_000_000, yoyChangePercent: 8.25, sectorAverageYoY: 6.5),
            GrowthDataPoint(period: "2025", value: 112_000_000_000, yoyChangePercent: 6.67, sectorAverageYoY: 5.2)
        ],
        netIncomeQuarterly: [
            GrowthDataPoint(period: "Q1 '24", value: 23_636_000_000, yoyChangePercent: 4.08, sectorAverageYoY: 3.2),
            GrowthDataPoint(period: "Q2 '24", value: 21_448_000_000, yoyChangePercent: 7.89, sectorAverageYoY: 5.5),
            GrowthDataPoint(period: "Q3 '24", value: 25_012_000_000, yoyChangePercent: 12.45, sectorAverageYoY: 8.9),
            GrowthDataPoint(period: "Q4 '24", value: 33_916_000_000, yoyChangePercent: 7.12, sectorAverageYoY: 5.8)
        ],
        operatingProfitAnnual: [
            GrowthDataPoint(period: "2020", value: 66_288_000_000, yoyChangePercent: 3.50, sectorAverageYoY: 2.8),
            GrowthDataPoint(period: "2021", value: 108_949_000_000, yoyChangePercent: 64.35, sectorAverageYoY: 42.1),
            GrowthDataPoint(period: "2022", value: 119_437_000_000, yoyChangePercent: 9.63, sectorAverageYoY: 6.5),
            GrowthDataPoint(period: "2023", value: 114_301_000_000, yoyChangePercent: -4.30, sectorAverageYoY: -5.2),
            GrowthDataPoint(period: "2024", value: 125_000_000_000, yoyChangePercent: 9.36, sectorAverageYoY: 7.8),
            GrowthDataPoint(period: "2025", value: 132_000_000_000, yoyChangePercent: 5.60, sectorAverageYoY: 4.5)
        ],
        operatingProfitQuarterly: [
            GrowthDataPoint(period: "Q1 '24", value: 27_900_000_000, yoyChangePercent: 5.12, sectorAverageYoY: 4.2),
            GrowthDataPoint(period: "Q2 '24", value: 25_350_000_000, yoyChangePercent: 8.45, sectorAverageYoY: 6.1),
            GrowthDataPoint(period: "Q3 '24", value: 29_600_000_000, yoyChangePercent: 10.23, sectorAverageYoY: 7.8),
            GrowthDataPoint(period: "Q4 '24", value: 41_150_000_000, yoyChangePercent: 6.78, sectorAverageYoY: 5.2)
        ],
        freeCashFlowAnnual: [
            GrowthDataPoint(period: "2020", value: 73_365_000_000, yoyChangePercent: 25.00, sectorAverageYoY: 18.5),
            GrowthDataPoint(period: "2021", value: 92_953_000_000, yoyChangePercent: 26.70, sectorAverageYoY: 22.3),
            GrowthDataPoint(period: "2022", value: 111_443_000_000, yoyChangePercent: 19.89, sectorAverageYoY: 15.8),
            GrowthDataPoint(period: "2023", value: 99_584_000_000, yoyChangePercent: -10.64, sectorAverageYoY: -8.2),
            GrowthDataPoint(period: "2024", value: 108_000_000_000, yoyChangePercent: 8.45, sectorAverageYoY: 6.5),
            GrowthDataPoint(period: "2025", value: 115_000_000_000, yoyChangePercent: 6.48, sectorAverageYoY: 5.2)
        ],
        freeCashFlowQuarterly: [
            GrowthDataPoint(period: "Q1 '24", value: 24_160_000_000, yoyChangePercent: 8.92, sectorAverageYoY: 6.5),
            GrowthDataPoint(period: "Q2 '24", value: 22_310_000_000, yoyChangePercent: 5.45, sectorAverageYoY: 4.2),
            GrowthDataPoint(period: "Q3 '24", value: 26_540_000_000, yoyChangePercent: 12.30, sectorAverageYoY: 9.8),
            GrowthDataPoint(period: "Q4 '24", value: 34_990_000_000, yoyChangePercent: 7.89, sectorAverageYoY: 6.1)
        ]
    )
}

// MARK: - Growth Info Item (for educational content)
struct GrowthInfoItem: Identifiable {
    let id = UUID()
    let title: String
    let description: String
    let icon: String
    let example: String?

    init(title: String, description: String, icon: String, example: String? = nil) {
        self.title = title
        self.description = description
        self.icon = icon
        self.example = example
    }
}

extension GrowthInfoItem {
    static let valueInvestingTips: [GrowthInfoItem] = [
        GrowthInfoItem(
            title: "Consistent Growth",
            description: "Look for companies with steady, predictable growth rates rather than volatile or erratic patterns. Warren Buffett prefers 'wonderful companies at fair prices.'",
            icon: "chart.line.uptrend.xyaxis",
            example: "A company growing revenue 8-12% annually for 5+ years is more reliable than one with 50% one year and -20% the next."
        ),
        GrowthInfoItem(
            title: "Compare to Sector",
            description: "The sector average line shows how the company performs relative to peers. Outperforming the sector consistently indicates competitive advantages.",
            icon: "chart.bar.fill",
            example: "If sector grows 5% but company grows 10%, it's gaining market share."
        ),
        GrowthInfoItem(
            title: "Revenue Quality",
            description: "Sustainable revenue growth comes from increasing sales volume or pricing power, not one-time events. Check if growth is organic or from acquisitions.",
            icon: "dollarsign.circle.fill",
            example: "Recurring subscription revenue is more valuable than one-time product sales."
        ),
        GrowthInfoItem(
            title: "EPS vs Revenue",
            description: "EPS growing faster than revenue suggests improving margins and operational efficiency. The opposite may indicate rising costs eating into profits.",
            icon: "arrow.up.right.circle.fill",
            example: "Revenue +5% with EPS +15% = excellent cost management."
        ),
        GrowthInfoItem(
            title: "Free Cash Flow",
            description: "FCF growth is crucial - it shows actual cash generation after all capital needs. Companies can manipulate earnings but not cash flow easily.",
            icon: "banknote.fill",
            example: "Positive FCF growth means the company can fund dividends, buybacks, or expansion without debt."
        ),
        GrowthInfoItem(
            title: "Year-over-Year (YoY)",
            description: "YoY comparison removes seasonality effects and shows true growth trajectory. Multiple positive YoY quarters indicate momentum.",
            icon: "calendar",
            example: "Comparing Q4 2024 to Q4 2023 is more meaningful than Q4 to Q3."
        )
    ]
}
