//
//  ReadAlongModels.swift
//  ios
//
//  Shared read-along timing models. As narration plays, the UI highlights the span (a sentence
//  for the Book Library + Money Moves, a word for the Investor Journey) whose [start, end) contains
//  the current playhead. One struct serves all three surfaces.
//
//  These are Decodable so backend-served content (Money Moves `content` JSONB, Journey
//  `story_content` JSONB) can carry timings inline. The Book Library bakes them into the static
//  table in BookReadAlong.swift (generated by backend/scripts/gen_book_read_along.py).
//

import Foundation

/// One timed text span with its start/end offset (seconds) within the currently-playing audio file.
struct ReadAlongSentence: Decodable, Equatable {
    let text: String
    let start: Double
    let end: Double
}

extension ReadAlongSentence {
    private enum CodingKeys: String, CodingKey { case text, start, end }

    /// Defensive decode. A single backend-served span with a null / missing / non-numeric
    /// `start` or `end` must NOT throw — synthesized array decoding is all-or-nothing, so one
    /// bad span would otherwise fail the decode of the ENTIRE Learn response and silently drop
    /// all remote lessons/articles (no audio, no read-along, stale content). Defining this in an
    /// extension preserves the synthesized memberwise init used by the book read-along table.
    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        self.text = ((try? c.decodeIfPresent(String.self, forKey: .text)) ?? nil) ?? ""
        let s = (try? c.decodeIfPresent(Double.self, forKey: .start)) ?? nil
        let e = (try? c.decodeIfPresent(Double.self, forKey: .end)) ?? nil
        let safeStart = (s?.isFinite == true) ? s! : 0
        let safeEnd = (e?.isFinite == true) ? e! : safeStart
        self.start = safeStart
        self.end = max(safeEnd, safeStart)   // a degenerate span just never highlights; it never crashes
    }
}

/// The Investor Journey highlights at word granularity; a word is the same timed span as a sentence.
typealias ReadAlongWord = ReadAlongSentence

/// A narrated block (heading or paragraph) with its per-sentence timings — used by the Book Library
/// read-along table (BookReadAlong.swift) and rendered by ReadAlongBlockView.
struct ReadAlongBlock: Equatable {
    let isHeading: Bool
    let sentences: [ReadAlongSentence]
}
