//
//  ReadAlongModels.swift
//  ios
//
//  Shared read-along timing models. As narration plays, the UI highlights the span (a sentence
//  for the Book Library + Money Moves, a word for the Investor Journey) whose [start, end) contains
//  the current playhead. One struct serves all three surfaces.
//
//  These are Decodable so backend-served content (Money Moves `content` JSONB, Journey
//  `story_content` JSONB) can carry timings inline. The Book Library bakes them into the static
//  table in BookReadAlong.swift (generated by backend/scripts/gen_book_read_along.py).
//

import Foundation

/// One timed text span with its start/end offset (seconds) within the currently-playing audio file.
struct ReadAlongSentence: Decodable, Equatable {
    let text: String
    let start: Double
    let end: Double
}

/// The Investor Journey highlights at word granularity; a word is the same timed span as a sentence.
typealias ReadAlongWord = ReadAlongSentence

/// A narrated block (heading or paragraph) with its per-sentence timings — used by the Book Library
/// read-along table (BookReadAlong.swift) and rendered by ReadAlongBlockView.
struct ReadAlongBlock: Equatable {
    let isHeading: Bool
    let sentences: [ReadAlongSentence]
}
