-- 128_learn_media_buckets_private.sql
--
-- ✅ APPLIED. Verified 2026-08-14 by probing a public object URL:
--      GET .../object/public/journey-media/audio/<clip>.m4a
--      → HTTP 400  {"statusCode":"404","error":"Bucket not found"}
--    All three buckets are private; the *_public_read policies are gone from
--    schema_snapshot.sql. The "DO NOT APPLY YET" banner this file carried for weeks after
--    it was applied is what made two later reviews reach the wrong conclusion — hence the
--    stamp. LAUNCH_CHECKLIST.md agrees.
--
-- Why: Wiser narration is Pro/Max (see services/entitlements.LEARN_AUDIO_UNLOCKED_TIERS),
-- but all three audio buckets are PUBLIC — 061 (journey-media), 065 (money-moves-media),
-- 068 (book-media) each created a bucket with anon+authenticated read so AVPlayer could
-- stream the URL directly. Every object path is deterministic, and the clip NAMES ship
-- inside the app bundle (207 in Resources/Journey/journey_lessons.json, 13 in
-- Resources/MoneyMoves/money_moves.json; book URLs were compiled straight into
-- BookAudioContent.swift until the signed-URL change). So anyone with a build can
-- reconstruct every URL offline.
--
-- That makes the shipped gate OBSCURITY, not enforcement: stripping `audioUrl` from the
-- JSON withholds nothing, because the object is still world-readable. This migration is
-- what actually closes it.
--
-- ── PRECONDITION — this is a ONE-WAY DOOR for installed builds ───────────────────────────
--
-- Applying this instantly breaks narration in EVERY already-installed build: shipped copies
-- of BookAudioContent.swift carry baked public URLs, and any Learn payload already cached on
-- a device carries public URLs too. There is no client-side recovery.
--
-- Apply ONLY when all of these hold:
--   1. No build in anyone's hands still uses public URLs — no App Store release, and no
--      TestFlight testers on an older build. (As of 2026-08-12 the App Store Connect record
--      does not exist yet — LAUNCH_CHECKLIST §"START HERE" item #4 — so this is satisfiable
--      now, but re-check before applying.)
--   2. /learn/journey, /learn/money-moves and /learn/books/audio have been serving SIGNED
--      urls in production, and the logs show no
--      `learn_audio_urls: signing bucket=... failed` warnings.
--
-- Point 2 matters more than it looks. `learn_audio_urls` degrades a signing failure by
-- falling back to the STORED PUBLIC URL, which still plays today — so a broken signing path
-- is currently invisible. After this migration that same fallback becomes a dead URL and an
-- AVPlayer error. Signing health must be proven WHILE the fallback is still masking it.
--
-- Until this is applied, nothing is enforced. The signed-URL work exists so that the flip is
-- a single migration with no client change and no coordinated release — it does not, by
-- itself, close the hole.
--
-- Not touched: the three *_service_write policies. The seed scripts
-- (seed_journey.py / seed_money_moves.py / seed_book_audio.py) run as service_role and must
-- keep working. service_role also bypasses RLS for the reads that mint signed URLs.
--
-- ── RESOLVED: the imageUrl question this file used to raise ──────────────────────────────
--
-- This warned that only `audioUrl` is signed, so populating a Journey card's `imageUrl` or
-- `videoUrl` from `journey-media` would break lesson artwork silently. Migration 136
-- answered it: all 27 lessons now carry an `imageUrl`, and it points at the SEPARATE PUBLIC
-- `journey-images` bucket, deliberately unsigned so it caches on device. Nothing artwork-
-- related lives in `journey-media`.
--
-- So the old check below now returns 27 and reads as an alarm that isn't one. The real
-- assertion is that no imageUrl/videoUrl points at a PRIVATE bucket:
--   select count(*) from lessons
--    where story_content::text like '%"imageUrl": "%journey-media%'
--       or story_content::text like '%"videoUrl": "%journey-media%';   -- must be 0
--
-- ── Journey narration is now FREE on every tier (2026-08-14) ─────────────────────────────
--
-- This does NOT reopen the bucket. `journey-media` stays private and every caller — free,
-- guest and paid — is served a signed URL by `sign_journey`, which is why that path now
-- carries 100% of Journey traffic rather than the Pro slice. Money Moves and book narration
-- are still Pro/Max. See entitlements.JOURNEY_AUDIO_UNLOCKED_TIERS.

-- 1. Flip the three Learn media buckets to private (idempotent).
UPDATE storage.buckets
   SET public = false
 WHERE id IN ('journey-media', 'money-moves-media', 'book-media');

-- 2. Remove anonymous/authenticated read. After this the ONLY read path is a signed URL
--    minted by app/services/learn_audio_urls.py on the service-role key.
--
-- DESTRUCTIVE (policy-level, not data): revokes public read of every object in these three
-- buckets. No rows are deleted and no audio is removed — re-running 061/065/068 restores the
-- previous state exactly if this needs to be rolled back.
DROP POLICY IF EXISTS "journey_media_public_read"     ON storage.objects;
DROP POLICY IF EXISTS "money_moves_media_public_read" ON storage.objects;
DROP POLICY IF EXISTS "book_media_public_read"        ON storage.objects;

-- Verification after applying (expect 403/400, not 200):
--   curl -sI "$SUPABASE_URL/storage/v1/object/public/book-media/audio/1_rich-dad-poor-dad.m4a"
-- and, with a Pro bearer, that this still returns a playable signed URL:
--   curl -s "$API/api/v1/learn/books/audio" -H "Authorization: Bearer $TOKEN"
