-- 137_money_moves_images.sql
--
-- Why: every Money Moves surface is text-only art today. The catalog card is a 200pt tile
-- with an SF Symbol badge, the article hero is a flat LinearGradient plus a procedural
-- grain Canvas, and the See-All "featured" card is a flat orange slab that ignores even
-- the authored gradient. This adds real cover artwork: one editorial plate per article,
-- generated by scripts/generate_money_moves_art.py and published by scripts/seed_money_moves.py.
--
-- Layout: money-moves-images/articles/<slug>.hero.jpg   1206x678 (16:9)
--         money-moves-images/articles/<slug>.card.jpg    640x360 (16:9)
--
--   .hero.jpg  the contained article header card AND the See-All featured card
--   .card.jpg  the 200pt catalog tile and the related-article tiles. A separate, smaller
--              object on purpose: a 13-card horizontal scroll row must not pull 1206px
--              images into 600px slots.
--
-- <slug> is the `slug` field from money_moves.json — the SAME key scripts/seed_money_moves.py
-- feeds to uuid5 for the money_move_articles row id, so the Storage path and the database
-- identity can never drift apart. Roughly 1.6 MB across all 26 objects for the 13 articles.
--
-- ⚠️ THIS BUCKET IS PUBLIC ON PURPOSE AND MUST STAY PUBLIC.
-- 128_learn_media_buckets_private.sql (APPLIED) flipped journey-media / money-moves-media /
-- book-media to private because narration is a paid (Pro/Max) feature. ARTWORK IS FREE and
-- must render for a locked, signed-out reader. Two independent reasons it lives in its own
-- bucket rather than in money-moves-media:
--
--   1. money-moves-media is ALREADY private, so a plate stored there would 404 outright.
--      The iOS AsyncImage error phase falls back to the article's gradient — no crash, no
--      log, no toast — so the art would silently never appear and nothing would report it.
--   2. Signed URLs are re-minted with a fresh ?token= every few hours (24h signature, 6h
--      memo — app/services/learn_audio_urls.py), and iOS URLCache keys on the whole URL, so
--      every plate would re-download several times a day forever. A stable public URL caches
--      indefinitely. Narration accepts that cost because its bucket must be private and
--      there is no alternative; free artwork does not have to, and should not.
--
-- Therefore: never add money-moves-images to 128's flip list, and never add it to
-- app/services/learn_audio_urls.py::_SIGNABLE_BUCKETS. Also note that
-- learn_audio_gate.redact_money_moves must keep leaving the image keys alone — it strips
-- narration for locked callers, and stripping the artwork with it would hide free content
-- behind the paywall. Pinned by tests/test_money_moves_art_parity.py.
--
-- Mirrors 136_journey_images_bucket.sql's `journey-images` and 133_book_covers_bucket.sql's
-- `book-covers`, both public for exactly the same reason.
--
-- Idempotent: safe to re-run.

-- A public bucket is world-readable AND world-listable by the shipped anon key, so nothing
-- non-public may ever be put here. The mime/size limits mirror 136: they cap what a holder
-- of the service_role key could serve from our own Supabase domain. Plates run ~50-160 KB
-- each; 2 MB is generous. Note DO UPDATE re-publicizes a bucket someone had made private —
-- that is the intended enforcement of "must stay public", matching 133 and 136.
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('money-moves-images', 'money-moves-images', true, 2097152, ARRAY['image/jpeg'])
ON CONFLICT (id) DO UPDATE
    SET public = EXCLUDED.public,
        file_size_limit = EXCLUDED.file_size_limit,
        allowed_mime_types = EXCLUDED.allowed_mime_types;

-- Anyone may read article artwork, signed in or not, free tier or paid. This is the whole
-- point of the bucket.
DROP POLICY IF EXISTS "money_moves_images_public_read" ON storage.objects;
CREATE POLICY "money_moves_images_public_read" ON storage.objects
    FOR SELECT TO anon, authenticated
    USING (bucket_id = 'money-moves-images');

-- Only the seed script (service_role) writes. Mirrors journey_images_service_write.
DROP POLICY IF EXISTS "money_moves_images_service_write" ON storage.objects;
CREATE POLICY "money_moves_images_service_write" ON storage.objects
    FOR ALL TO service_role
    USING (bucket_id = 'money-moves-images')
    WITH CHECK (bucket_id = 'money-moves-images');

-- The hero URL as a first-class column, alongside audio_url from 065.
--
-- The full set of URLs lives in the `content` JSONB (imageUrl / imageCardUrl), which is what
-- iOS actually decodes — the endpoint serves that blob verbatim, which is why new artwork
-- reaches installed apps with no App Store release. This column exists for the two things
-- JSONB is bad at: answering "which articles still have no art?" without scanning every
-- blob, and letting MoneyMovesContentService overlay an authoritative value onto the blob
-- exactly as it already does for audio_url. Nullable because an article without a generated
-- plate is a normal state, not an error — it simply falls back to its heroGradientColors.
ALTER TABLE public.money_move_articles
    ADD COLUMN IF NOT EXISTS image_url TEXT;

COMMENT ON COLUMN public.money_move_articles.image_url IS
    'Public URL of the 1206x678 hero plate in the money-moves-images bucket. Authoritative '
    'over content->>''imageUrl''. NULL means no artwork yet; iOS falls back to heroGradientColors.';

-- Partial index: the only query that uses this column is the backfill check for articles
-- still missing artwork, so index exactly those rows and nothing else.
CREATE INDEX IF NOT EXISTS idx_money_move_articles_missing_art
    ON public.money_move_articles (sort_order)
    WHERE image_url IS NULL;

-- Verify immediately after applying (expect 400/404 — NOT 403, which would mean the public
-- read policy did not take):
--   curl -sI "$SUPABASE_URL/storage/v1/object/public/money-moves-images/articles/the-fall-of-enron.hero.jpg"
-- Then re-run after scripts/seed_money_moves.py and expect HTTP 200.
