"""Response shapes for GET /learn/books/audio.

Book narration is one .m4a per book covering every core in order. Until now its URL was
COMPILED INTO THE APP (`frontend/ios/ios/Models/BookAudioContent.swift`, generated by
`scripts/gen_book_audio_swift.py`) and pointed at the public `book-media` bucket, so anyone
reading a single network request could stream all 276 MB regardless of plan. This endpoint
replaces that: the URL becomes a short-lived signed URL fetched at play time.

What deliberately does NOT move here: `totalSeconds` and `coreStartSeconds`. Those stay
compiled into the app because they drive FREE UI that advertises the narration — the
per-core "2:37" labels in the book timeline, the current-core readout in the full-screen
player, and the auto-advance maths. A locked caller must still see all of that.
"""

from typing import List, Optional

from pydantic import BaseModel, Field


class BookAudioURLResponse(BaseModel):
    """One book's playable narration URL."""

    curriculum_order: int = Field(..., description="LibraryBook.curriculumOrder, 1-based")
    audio_url: str = Field(..., description="Signed, expiring Storage URL for the whole book")


class BooksAudioResponse(BaseModel):
    """Envelope for the book narration URLs.

    A locked caller gets HTTP **200** with an empty ``books`` list and ``audio_locked=True``
    — NOT a 403. That matches the two sibling Learn routes (`/journey`, `/money-moves`),
    which also answer 200-with-a-locked-flag, and it keeps the client's error pipeline out
    of a screen whose whole job is to render an upgrade offer. iOS refuses playback at the
    player entry points (`LearnAudioEntitlement`), so the empty list is belt-and-braces on
    the wire rather than the gate itself.
    """

    books: List[BookAudioURLResponse] = []
    # All defaulted so an already-shipped client decodes this unchanged.
    audio_locked: bool = False
    tier_required: Optional[str] = None

    # THE THIRD STATE. Without it, "Storage refused to sign anything just now" is
    # wire-identical to "this account is entitled and no book has narration" — both are
    # `{"books": [], "audio_locked": false}`. The client must not treat the first as the
    # second: it caches URLs, and an unlocked-empty response would otherwise DELETE ten
    # perfectly good ones and leave every Play button dead until the next fetch.
    #
    # True means: keep whatever you already have, show no lock, try again later.
    temporarily_unavailable: bool = False
