//
//  BulletTextFormatting.swift
//  ios
//
//  Small display normalization for AI summary bullets.
//

import Foundation

/// Opening clauses that are pure scaffolding in front of a conclusion.
///
/// Kept in ONE place because two separate backend prompts used to ask for these
/// (`news_insight_service._build_prompt` for the Insights card,
/// `news_cache_service._batch_enrich_articles` for per-article bullets). Both now
/// forbid them, but see `strippingConclusionLeadIn()` for why that is not enough.
///
/// TWO CLASSES, and the split is load-bearing:
///
/// `exact` stems must BE the whole clause. "So," is a lead-in; "So the Fed cut
/// rates," is a sentence that happens to start with the same word, and allowing a
/// continuation here would delete it.
///
/// `openNoun` stems may be followed by a few more words, because their head noun
/// cannot begin an ordinary clause that means anything else — which is what makes
/// "The takeaway for everyday investors," (the form actually observed in
/// production) safe to match while "So the Fed…" is not.
private let conclusionLeadInExactStems: [[String]] = [
    ["so"],
    ["so", "what"],
    ["in", "short"],
    ["in", "summary"],
    ["in", "brief"],
    ["ultimately"],
    ["overall"],
    ["bottom", "line"],
    ["the", "bottom", "line"],
    ["net-net"],
    ["what", "this", "means"],
    ["what", "it", "means"],
]

private let conclusionLeadInOpenNounStems: [[String]] = [
    ["the", "takeaway"],
    ["takeaway"],
    ["key", "takeaway"],
    ["the", "key", "takeaway"],
    ["the", "upshot"],
    ["upshot"],
]

/// A real lead-in is short. Past this the clause is carrying content.
private let conclusionLeadInMaxWords = 6

extension String {
    /// Rewrites a short lead-in transition that ends in a colon into a
    /// comma-led sentence, e.g. `"The takeaway: This policy…"` →
    /// `"The takeaway, This policy…"` and `"In short: X"` → `"In short, X"`.
    ///
    /// Applied to the FINAL summary bullet (the "why investors care" line) so it
    /// reads like the other transitions ("Ultimately, …") instead of a bold
    /// label. Only a colon within the first `maxLeadIn` characters is touched, so
    /// a legitimate mid-sentence colon (e.g. "watch two things: X and Y") is left
    /// alone. This is a display-time safeguard for already-cached bullets; new
    /// enrichments are prompted to emit the comma directly.
    func normalizingLeadInColon(maxLeadIn: Int = 40) -> String {
        guard let colon = firstIndex(of: ":") else { return self }
        guard distance(from: startIndex, to: colon) <= maxLeadIn else { return self }
        let lead = self[..<colon]
        // Keep the sentence readable: drop spaces right after the colon so we
        // don't produce ",  " (double space).
        let rest = self[index(after: colon)...].drop(while: { $0 == " " })
        return "\(lead), \(rest)"
    }

    /// Removes a conclusion lead-in ("The takeaway for everyday investors, …",
    /// "In short, …") so only the point itself remains, re-capitalised.
    ///
    /// The conclusion bullet is marked with an icon now (`SummaryBulletGlyph`), so
    /// saying it in words is redundant. Both backend prompts have been changed to
    /// stop writing them — **and that is not sufficient**, which is the whole
    /// reason this exists:
    ///
    /// - the Insights card is regenerated by a `PROMPT_VERSION` bump, so it heals
    ///   on the next sweep;
    /// - per-article bullets have **no invalidation mechanism at all**. They are
    ///   re-enriched only when `ai_processed` is false, and `expires_at` is
    ///   re-stamped on every refresh, so an article that keeps circulating in the
    ///   feed keeps its old text indefinitely. Without this, the new icon would
    ///   land directly in front of the words it replaces.
    ///
    /// Falls back to `normalizingLeadInColon()` when no stem matches, so an
    /// unrecognised "Bottom line: X" still reads as a sentence rather than a label.
    ///
    /// - Warning: stems match on WORD boundaries, never as a raw prefix.
    ///   `"Sony, the electronics maker, …"` opens with the letters of the stem
    ///   `so`; a prefix test would eat the company's name, and the result would
    ///   read like a model error rather than a formatting bug.
    func strippingConclusionLeadIn(maxLeadIn: Int = 48) -> String {
        let clauseEnd = firstIndex(where: { $0 == "," || $0 == ":" || $0 == "\u{2014}" })
        guard let end = clauseEnd,
              distance(from: startIndex, to: end) <= maxLeadIn else {
            return normalizingLeadInColon()
        }

        // Compare on words, lowercased, with punctuation dropped so "So what?" and
        // "so what" are the same opener.
        let words = self[..<end]
            .lowercased()
            .split(whereSeparator: { !$0.isLetter && $0 != "-" })
            .map(String.init)
        guard !words.isEmpty, words.count <= conclusionLeadInMaxWords else {
            return normalizingLeadInColon()
        }
        let isExact = conclusionLeadInExactStems.contains(words)
        let isOpenNoun = conclusionLeadInOpenNounStems.contains { stem in
            words.count >= stem.count && Array(words.prefix(stem.count)) == stem
        }
        guard isExact || isOpenNoun else { return normalizingLeadInColon() }

        let rest = self[index(after: end)...]
            .trimmingCharacters(in: .whitespacesAndNewlines)
        // A lead-in with nothing behind it is not a lead-in. Returning "" here
        // would blank the one line the reader most needs.
        guard rest.count >= 20 else { return normalizingLeadInColon() }

        return rest.prefix(1).uppercased() + rest.dropFirst()
    }
}
