//
//  StoreScreenshotFixtures.swift
//  ios
//
//  DEBUG-ONLY sample data for `StoreScreenshotMode` (read that file's header first).
//
//  Every figure here is INVENTED, and every company that carries a price, a % move or a chart is
//  FICTIONAL (owner, 2026-10-08: no "Sample data" label — the rule's other branch, "on a fictional
//  ticker"). Each ticker and name below was checked against FMP's full stock list (93,922 symbols,
//  2026-10-08): no symbol exists, and no name's first word appears in a real company's name.
//  tests/test_ios_store_screenshot_mode_debug_only.py pins the allow-list — a real ticker here
//  would need the label back (`StoreScreenshotMode.showsLabel`). Series are generated by a formula, not typed out,
//  so the file holds no large literal (a giant Swift literal crashed this Mac: CLAUDE.md,
//  Machine safety rule 7).
//
//  Wire fixtures are built with JSONSerialization in the shape the backend's response models
//  emit, so they travel through the app's real decoders and mappers:
//    GET  /api/v1/tracking/assets          → schemas/tracking.py      TrackingFeedResponse
//    GET  /api/v1/portfolios               → endpoints/portfolios.py  PortfolioListResponse
//    GET  /api/v1/portfolios/{id}/insights → null (a group with no holdings has no score)
//    GET  /api/v1/updates/tabs             → schemas/updates.py       UpdatesTabsResponse
//    GET  /api/v1/updates/feed             → schemas/updates.py       UpdatesFeedResponse
//    GET  /api/v1/updates/sentiment-trend  → schemas/updates.py       SentimentTrendResponse
//  Writes the Tracking tab can trigger (its feed-driven ticker purge PUTs the active group's
//  tickers) are answered here and never reach the server — against a real account they would
//  delete real rows.
//
//  The Updates tab is shown ONLY because all three of its reads are answered here (2026-10-08):
//  its live Insights card is an AI brief seeded with real index % moves, and live headlines can
//  name real people. The sample feed is fictional, sector-level text — no person, no ticker, no
//  price or % figure — from fictional outlets, and the News Tone counts are a formula.
//
//  Home's themes and Trillion Club sections are left EMPTY, so they hide: their mock data carries
//  real theme names with invented % moves and real companies (`StoreShotHomeRepository`).
//

#if DEBUG
import Foundation
import SwiftUI

/// One sample holding — the same five on Home's holdings strip, the Tracking list and the
/// Updates chips, so the screenshots agree with each other.
nonisolated struct StoreShotHolding: Sendable {
    let symbol: String
    let name: String
    let price: Double
    let changePercent: Double
    let marketCap: Double
    let sector: String
}

/// One sample story for the Updates feed. Invented, sector-level text: no person, no ticker,
/// no price or % figure.
nonisolated struct StoreShotStory: Sendable {
    let headline: String
    let summary: String
    let sentiment: String
    let minutesAgo: Int
}

nonisolated enum StoreShotFixtures {
    static let portfolioId = "store-shot-sample"
    /// The watchlist's name on Tracking, Updates and Home.
    static let groupName = "My Watchlist"

    static let holdings: [StoreShotHolding] = [
        StoreShotHolding(symbol: "NRWD", name: "Northwind Robotics", price: 184.20, changePercent: 1.24,
                         marketCap: 2.84e11, sector: "Technology"),
        StoreShotHolding(symbol: "QLVN", name: "Quillvane Systems", price: 412.50, changePercent: 0.86,
                         marketCap: 3.07e11, sector: "Technology"),
        StoreShotHolding(symbol: "TRVK", name: "Trevik Semiconductors", price: 131.80, changePercent: 2.41,
                         marketCap: 3.24e11, sector: "Technology"),
        StoreShotHolding(symbol: "BRVX", name: "Brivex Biotech", price: 78.40, changePercent: -0.52,
                         marketCap: 4.1e10, sector: "Healthcare"),
        StoreShotHolding(symbol: "HLVA", name: "Helvara Cloud", price: 162.30, changePercent: 0.37,
                         marketCap: 2.01e11, sector: "Technology"),
    ]

    static func previousClose(of holding: StoreShotHolding) -> Double {
        holding.price / (1.0 + holding.changePercent / 100.0)
    }

    /// A smooth, deterministic intraday-shaped series from `start` to exactly `end`.
    static func series(seed: Int, count: Int, from start: Double, to end: Double) -> [Double] {
        var points: [Double] = []
        points.reserveCapacity(count)
        let span: Double = max(abs(end - start), start * 0.004)
        let phase: Double = Double(seed) * 1.7
        let last: Double = Double(max(count - 1, 1))
        for index in 0..<count {
            let t: Double = Double(index) / last
            let trend: Double = start + (end - start) * t
            let slow: Double = sin(t * 7.0 + phase) * 0.45
            let fast: Double = sin(t * 19.0 + phase * 2.3) * 0.2
            let taper: Double = 1.0 - t
            points.append(trend + (slow + fast) * span * taper)
        }
        return points
    }

    static func sparkline(for holding: StoreShotHolding, seed: Int) -> [Double] {
        series(seed: seed, count: 40, from: previousClose(of: holding), to: holding.price)
    }

    // MARK: Wire fixtures

    static func trackingFeedJSON() -> Data {
        var assets: [[String: Any]] = []
        for (index, holding) in holdings.enumerated() {
            var row: [String: Any] = [:]
            row["ticker"] = holding.symbol
            row["company_name"] = holding.name
            row["price"] = holding.price
            row["change_percent"] = holding.changePercent
            row["price_known"] = true
            row["change_known"] = true
            row["previous_close"] = previousClose(of: holding)
            row["sparkline_data"] = sparkline(for: holding, seed: index)
            row["spark_from"] = 0.0
            row["spark_to"] = 1.0
            row["logo_url"] = NSNull()
            row["sector"] = holding.sector
            row["country"] = "US"
            row["market_cap"] = holding.marketCap
            // No holding values: these are watchlist rows, so the holding fields are null.
            row["shares"] = NSNull()
            row["market_value"] = NSNull()
            row["asset_type"] = NSNull()
            assets.append(row)
        }
        let body: [String: Any] = ["assets": assets, "alerts": [Any]()]
        return json(body)
    }

    static func portfolioObject() -> [String: Any] {
        var items: [[String: Any]] = []
        for holding in holdings {
            items.append(["ticker": holding.symbol, "shares": NSNull(), "market_value": NSNull()])
        }
        var portfolio: [String: Any] = [:]
        portfolio["id"] = portfolioId
        portfolio["name"] = groupName
        portfolio["sort_order"] = 0
        portfolio["items"] = items
        portfolio["created_at"] = "2026-10-01T00:00:00Z"
        portfolio["updated_at"] = "2026-10-01T00:00:00Z"
        portfolio["is_active"] = true
        return portfolio
    }

    static func portfoliosJSON() -> Data {
        json(["portfolios": [portfolioObject()]])
    }

    /// The answer to any portfolio WRITE: the unchanged sample group (`PortfolioResponse`).
    static func portfolioJSON() -> Data {
        json(portfolioObject())
    }

    static func updatesTabsJSON() -> Data {
        var tabs: [[String: Any]] = []
        var market: [String: Any] = [:]
        market["scope"] = "__MARKET__"
        market["title"] = "Market"
        market["company_name"] = NSNull()
        market["change_percent"] = NSNull()
        market["logo_url"] = NSNull()
        market["is_market_tab"] = true
        market["is_locked"] = false
        market["asset_type"] = NSNull()
        tabs.append(market)
        for holding in holdings {
            var tab: [String: Any] = [:]
            tab["scope"] = holding.symbol
            tab["title"] = holding.symbol
            tab["company_name"] = holding.name
            tab["change_percent"] = holding.changePercent
            tab["logo_url"] = NSNull()
            tab["is_market_tab"] = false
            tab["is_locked"] = false
            tab["asset_type"] = "stock"
            tabs.append(tab)
        }
        var body: [String: Any] = [:]
        body["tabs"] = tabs
        body["group_name"] = groupName
        body["locked_count"] = 0
        body["tier_required"] = NSNull()
        return json(body)
    }

    // MARK: Updates feed (invented text, no figures)

    static let marketScope = "__MARKET__"
    static let sampleSources: [String] = ["Harborline News", "Ledgerpoint", "Briefwire Daily"]

    static let sampleStories: [StoreShotStory] = [
        StoreShotStory(headline: "Stocks hold steady as traders look ahead to inflation data",
                       summary: "Major indexes drifted in a narrow range while investors waited for next week's inflation report.",
                       sentiment: "Neutral", minutesAgo: 18),
        StoreShotStory(headline: "Chipmakers extend their rally on a stronger AI spending outlook",
                       summary: "Semiconductor shares led technology higher as cloud providers signaled more data-center investment.",
                       sentiment: "Positive", minutesAgo: 52),
        StoreShotStory(headline: "Oil slips as supply worries ease",
                       summary: "Crude prices fell after inventories rose more than expected, weighing on energy shares.",
                       sentiment: "Negative", minutesAgo: 95),
        StoreShotStory(headline: "Bank earnings set the tone for the reporting season",
                       summary: "Large lenders open the quarter's results, with investors focused on loan growth and credit quality.",
                       sentiment: "Neutral", minutesAgo: 140),
        StoreShotStory(headline: "Treasury yields ease ahead of the Fed minutes",
                       summary: "Bond yields moved lower as markets weighed the path of interest rates into next year.",
                       sentiment: "Positive", minutesAgo: 205),
        StoreShotStory(headline: "Retailers brace for a cautious holiday quarter",
                       summary: "Store chains point to careful consumer spending, with discounts expected to start early.",
                       sentiment: "Negative", minutesAgo: 270),
        StoreShotStory(headline: "Small caps gain as rate-cut hopes build",
                       summary: "Smaller companies outperformed as investors priced in lower borrowing costs.",
                       sentiment: "Positive", minutesAgo: 340),
        StoreShotStory(headline: "Dollar steadies against major currencies",
                       summary: "The currency held its range as traders awaited fresh economic data.",
                       sentiment: "Neutral", minutesAgo: 410),
    ]

    static let sampleInsightBullets: [String] = [
        "Technology and healthcare led, while energy lagged as oil eased.",
        "Rate expectations held steady ahead of next week's inflation report.",
        "Earnings season begins, with the large banks reporting first.",
    ]

    /// `GET /api/v1/updates/feed` — the sample stories and Insights card for the Market tab; an
    /// empty page for any other scope (no invented news on a real company). Ids start with
    /// "sample_", which the app never sends for enrichment, and `has_more` is false.
    static func updatesFeedJSON(scope: String, now: Date = Date()) -> Data {
        var body: [String: Any] = [:]
        body["scope"] = scope
        body["cached"] = true
        body["cache_age_seconds"] = 300
        body["offset"] = 0
        body["has_more"] = false
        guard scope == marketScope else {
            body["articles"] = [Any]()
            body["insight"] = NSNull()
            return json(body)
        }
        var articles: [[String: Any]] = []
        for (index, story) in sampleStories.enumerated() {
            let published: Date = now.addingTimeInterval(-Double(story.minutesAgo) * 60.0)
            var row: [String: Any] = [:]
            row["id"] = "sample_\(index + 1)"
            row["headline"] = story.headline
            row["summary"] = story.summary
            row["summary_bullets"] = [story.summary]
            row["sentiment"] = story.sentiment
            row["source_name"] = sampleSources[index % sampleSources.count]
            row["source_logo_url"] = NSNull()
            row["published_at"] = isoUTC(published)
            row["thumbnail_url"] = NSNull()
            row["article_url"] = NSNull()
            row["related_tickers"] = [String]()
            row["ai_processed"] = true
            articles.append(row)
        }
        var sources: [[String: Any]] = []
        for (index, story) in sampleStories.prefix(3).enumerated() {
            sources.append(["title": story.headline, "url": "", "publisher": sampleSources[index]])
        }
        var insight: [String: Any] = [:]
        insight["scope"] = scope
        insight["headline"] = "Markets steady as investors weigh rates and earnings"
        insight["bullets"] = sampleInsightBullets
        insight["sentiment"] = "Neutral"
        insight["badge"] = "48h"
        insight["article_count"] = sampleStories.count
        insight["generated_at"] = isoUTC(now.addingTimeInterval(-25.0 * 60.0))
        insight["is_stale"] = false
        insight["refreshing"] = false
        insight["ai_generated"] = true
        insight["trigger_reason"] = NSNull()
        insight["price_move"] = NSNull()
        insight["sources"] = sources
        body["articles"] = articles
        body["insight"] = insight
        return json(body)
    }

    // MARK: News Tone (invented counts)

    /// `GET /api/v1/updates/sentiment-trend` — `days` ET calendar days ending TODAY in New York
    /// (the app's axis ends there), today's bar partial, and a `tracking_since` long before every
    /// window, so the chart reads as fully covered and the legend shows no coverage note (the app
    /// shows one only for an incomplete chart). The counts look like real news (owner,
    /// 2026-10-08: "up and down like random"): a mood that random-walks between positive and
    /// negative streaks, uneven daily volume, quieter weekends and the odd news-heavy day — all
    /// from a deterministic hash of the DATE, so a re-capture draws the same bars.
    static func sentimentTrendJSON(scope: String, days requested: Int, now: Date = Date()) -> Data {
        let count: Int = max(1, min(requested, 90))
        let calendar: Calendar = easternCalendar
        let today: Date = calendar.startOfDay(for: now)
        var series: [[String: Any]] = []
        var mood: Double = 0.0
        for index in 0..<count {
            let offset: Int = count - 1 - index
            guard let date = calendar.date(byAdding: .day, value: -offset, to: today) else { continue }
            let day: Int = ordinalDay(date)
            let step: Double = (2.0 * noise(day: day, salt: 2) - 1.0) * 1.6
            mood = max(-1.0, min(1.0, 0.35 * mood + 0.65 * step))
            var positiveShare: Double = 0.40 + 0.42 * mood + 0.30 * (noise(day: day, salt: 3) - 0.5)
            var negativeShare: Double = 0.32 - 0.38 * mood + 0.30 * (noise(day: day, salt: 4) - 0.5)
            positiveShare = min(max(positiveShare, 0.06), 0.86)
            negativeShare = min(max(negativeShare, 0.05), 0.82)
            let shareSum: Double = positiveShare + negativeShare
            if shareSum > 0.95 {
                positiveShare *= 0.95 / shareSum
                negativeShare *= 0.95 / shareSum
            }
            var volume: Double = 8.0 + 30.0 * noise(day: day, salt: 1)
            let weekday: Int = calendar.component(.weekday, from: date)
            if weekday == 1 || weekday == 7 { volume *= 0.5 }
            if noise(day: day, salt: 5) > 0.84 { volume *= 2.0 }
            if offset == 0 { volume *= 0.45 }
            let total: Int = max(2, Int(volume.rounded()))
            let positive: Int = Int((Double(total) * positiveShare).rounded())
            let negative: Int = Int((Double(total) * negativeShare).rounded())
            let neutral: Int = max(0, total - positive - negative)
            let sum: Int = positive + negative + neutral
            let net: Int = sum > 0 ? Int((Double(positive - negative) * 100.0 / Double(sum)).rounded()) : 0
            var row: [String: Any] = [:]
            row["date"] = easternDayKey(date)
            row["bullish"] = positive
            row["bearish"] = negative
            row["neutral"] = neutral
            row["total"] = sum
            row["net_score"] = net
            row["is_partial"] = offset == 0
            series.append(row)
        }
        let since: Date = calendar.date(byAdding: .day, value: -150, to: today) ?? today
        var body: [String: Any] = [:]
        body["scope"] = scope
        body["days"] = count
        body["series"] = series
        body["tracking_since"] = easternDayKey(since)
        body["history_status"] = "ready"
        return json(body)
    }

    /// Deterministic noise in [0, 1) for one calendar day and stream: splitmix64's finalizer
    /// over the day number, so the same date always draws the same value.
    static func noise(day: Int, salt: Int) -> Double {
        var x: UInt64 = UInt64(truncatingIfNeeded: day) &* 0x9E37_79B9_7F4A_7C15
        x = x &+ UInt64(truncatingIfNeeded: salt) &* 0xBF58_476D_1CE4_E5B9
        x = x &+ 0x94D0_49BB_1331_11EB
        x ^= x >> 30
        x = x &* 0xBF58_476D_1CE4_E5B9
        x ^= x >> 27
        x = x &* 0x94D0_49BB_1331_11EB
        x ^= x >> 31
        return Double(x >> 11) / 9_007_199_254_740_992.0
    }

    /// The proleptic-Gregorian day number of an ET calendar day (Python's `date.toordinal()`):
    /// a stable integer per DATE for `noise`.
    static func ordinalDay(_ date: Date) -> Int {
        let parts: DateComponents = easternCalendar.dateComponents([.year, .month, .day], from: date)
        var utc = Calendar(identifier: .gregorian)
        utc.timeZone = TimeZone(identifier: "UTC") ?? .current
        let midnight: Date = utc.date(from: parts) ?? date
        return Int((midnight.timeIntervalSince1970 / 86_400.0).rounded(.down)) + 719_163
    }

    static let easternCalendar: Calendar = {
        var calendar = Calendar(identifier: .gregorian)
        calendar.timeZone = TimeZone(identifier: "America/New_York") ?? .current
        return calendar
    }()

    static func easternDayKey(_ date: Date) -> String {
        let formatter = DateFormatter()
        formatter.calendar = easternCalendar
        formatter.locale = Locale(identifier: "en_US_POSIX")
        formatter.timeZone = easternCalendar.timeZone
        formatter.dateFormat = "yyyy-MM-dd"
        return formatter.string(from: date)
    }

    static func isoUTC(_ date: Date) -> String {
        let formatter = ISO8601DateFormatter()
        formatter.formatOptions = [.withInternetDateTime]
        return formatter.string(from: date)
    }

    private static func json(_ object: Any) -> Data {
        do {
            return try JSONSerialization.data(withJSONObject: object)
        } catch {
            print("📸 [StoreScreenshotMode] fixture encode failed: \(type(of: error)): \(error)")
            return Data("{}".utf8)
        }
    }
}

// MARK: - Home

/// Home in screenshot mode: every price, % move and sparkline is INVENTED here, on FICTIONAL
/// indexes and companies (the previews' mock figures were not reused — some may once have been
/// copied from a live strip), the signals are LOCKED (a free account's shape — no invented
/// filings on real companies), and the holdings strip is the sample holdings.
final class StoreShotHomeRepository: HomeRepositoryProtocol {
    func fetchHomeDashboard() async throws -> HomeDashboardFetch {
        // No body: nothing is ever written to the on-device snapshot.
        HomeDashboardFetch(data: Self.dashboard, body: nil)
    }

    static var dashboard: HomeDashboardData {
        HomeDashboardData(
            marketStatusText: "Markets Open",
            marketIsOpen: true,
            pulse: samplePulse,
            scanners: [moversCard, volumeCard, shortsCard],
            signals: MockHomeRepository.lockedSignals,
            // EMPTY, so both sections hide (review 2026-10-08). The mock themes put invented %
            // moves on Caydex's real theme names, and the mock Trillion Club carries real
            // companies' filing figures — unlabelled, either could pass for real if a layout
            // change ever brought it into a frame.
            themes: [],
            watchlist: holdingsStrip,
            watchlistTitle: StoreShotFixtures.groupName,
            watchlistIsGroup: true,
            trillionClub: .empty
        )
    }

    // MARK: Market strip (invented values)

    private static var samplePulse: [MarketPulseItem] {
        var items: [MarketPulseItem] = []
        items.append(pulseItem("Quovex 500", "QVX5", .etf, price: 512.40, change: 0.48, seed: 11))
        items.append(pulseItem("Tallora 100", "TLVR", .etf, price: 168.20, change: 0.71, seed: 12))
        items.append(pulseItem("Brinmor 30", "BRN3", .etf, price: 421.30, change: 0.22, seed: 13))
        items.append(pulseItem("Kestova 2000", "KSV2", .etf, price: 205.60, change: -0.35, seed: 14))
        items.append(pulseItem("Aurelith Gold", "ARLX", .etf, price: 231.80, change: 0.15, seed: 15))
        items.append(pulseItem("Vynco Coin", "VYNC", .crypto, price: 64_250.00, change: 1.10, seed: 16))
        return items
    }

    private static func pulseItem(
        _ name: String, _ symbol: String, _ type: MarketTickerType,
        price: Double, change: Double, seed: Int
    ) -> MarketPulseItem {
        let previous: Double = price / (1.0 + change / 100.0)
        let priceText: String = price >= 10_000
            ? price.formatted(.number.precision(.fractionLength(2)))
            : String(format: "%.2f", price)
        return MarketPulseItem(
            name: name, symbol: symbol, type: type,
            priceText: priceText, changeText: percentText(change), isPositive: change >= 0,
            spark: StoreShotFixtures.series(seed: seed, count: 30, from: previous, to: price),
            previousClose: previous
        )
    }

    private static func percentText(_ change: Double) -> String {
        (change >= 0 ? "+" : "") + String(format: "%.2f%%", change)
    }

    // MARK: Daily Scanners (invented values)

    private static func entry(
        _ rank: Int, _ symbol: String, _ name: String,
        _ primary: String, _ secondary: String, _ up: Bool
    ) -> ScannerEntry {
        ScannerEntry(rank: rank, symbol: symbol, name: name,
                     primaryText: primary, secondaryText: secondary, isPositive: up)
    }

    /// Rank 1 carries the card's sparkline.
    private static func head(_ entry: ScannerEntry, seed: Int, rising: Bool) -> ScannerEntry {
        var withSpark = entry
        let low: Double = 100
        let high: Double = 106
        withSpark.spark = StoreShotFixtures.series(seed: seed, count: 30, from: rising ? low : high, to: rising ? high : low)
        return withSpark
    }

    private static var moversCard: DailyScanner {
        var gainers: [ScannerEntry] = []
        gainers.append(head(entry(1, "ZEPX", "Zephrix Motors", "+6.8%", "$62.40", true), seed: 21, rising: true))
        gainers.append(entry(2, "KLRO", "Kalero Foods", "+5.2%", "$48.10", true))
        gainers.append(entry(3, "VNTQ", "Ventiq Software", "+4.6%", "$171.30", true))
        gainers.append(entry(4, "PXLR", "Pixlar Media", "+4.1%", "$24.80", true))
        gainers.append(entry(5, "DRVA", "Dravia Materials", "+3.7%", "$38.20", true))
        var losers: [ScannerEntry] = []
        losers.append(head(entry(1, "GLNT", "Glennet Retail", "-5.4%", "$21.30", false), seed: 22, rising: false))
        losers.append(entry(2, "FNRX", "Fenrix Pharma", "-4.2%", "$81.50", false))
        losers.append(entry(3, "ALVQ", "Alvequa Airlines", "-3.6%", "$32.40", false))
        losers.append(entry(4, "BLNX", "Bellnex Telecom", "-3.1%", "$11.70", false))
        losers.append(entry(5, "SKVR", "Skyvera Aerospace", "-2.7%", "$90.90", false))
        return DailyScanner(
            kind: .movers, title: "Today's Top Movers", subtitle: "",
            iconSystemName: "chart.line.uptrend.xyaxis", accent: AppColors.bullish,
            expandCTA: "See full leaderboard", gainers: gainers, losers: losers
        )
    }

    private static var volumeCard: DailyScanner {
        var rows: [ScannerEntry] = []
        rows.append(head(entry(1, "NVLQ", "Novalq Mining", "6.2×", "+3.4%", true), seed: 23, rising: true))
        rows.append(entry(2, "TMRX", "Temrix Robotics", "4.8×", "+2.6%", true))
        rows.append(entry(3, "WVLN", "Wavelin Devices", "4.1×", "-1.9%", false))
        rows.append(entry(4, "JXTA", "Jextra Payments", "3.7×", "+4.2%", true))
        rows.append(entry(5, "LMRQ", "Lumarq Chemicals", "3.3×", "-2.8%", false))
        return DailyScanner(
            kind: .volume, title: "Heavy Traffic", subtitle: "Unusual trading volume",
            iconSystemName: "chart.bar.fill", accent: AppColors.accentCyan, badgeText: "Volume",
            expandCTA: "See all unusual volume", entries: rows
        )
    }

    private static var shortsCard: DailyScanner {
        var rows: [ScannerEntry] = []
        rows.append(head(entry(1, "HPRV", "Hyprova Batteries", "21.7%", "$45.10", false), seed: 24, rising: false))
        rows.append(entry(2, "YLDX", "Yeldex Insurance", "18.9%", "$32.40", false))
        rows.append(entry(3, "RQVN", "Requvon Biotech", "17.6%", "$27.30", false))
        rows.append(entry(4, "FLXQ", "Flexiq Apparel", "16.2%", "$13.10", false))
        rows.append(entry(5, "MRVQ", "Marvique Foods", "15.4%", "$12.60", false))
        return DailyScanner(
            kind: .shorts, title: "Skeptical Money", subtitle: "Highest short interest",
            iconSystemName: "eye.fill", accent: AppColors.neutral, badgeText: "Shorts",
            expandCTA: "See all high short interest",
            infoNote: "High short interest reflects skepticism — and can fuel a short squeeze if the stock rallies.",
            entries: rows
        )
    }

    private static var holdingsStrip: [MarketPulseItem] {
        var items: [MarketPulseItem] = []
        for (index, holding) in StoreShotFixtures.holdings.enumerated() {
            let item = MarketPulseItem(
                name: holding.name,
                symbol: holding.symbol,
                type: .stock,
                priceText: String(format: "%.2f", holding.price),
                changeText: percentText(holding.changePercent),
                isPositive: holding.changePercent >= 0,
                spark: StoreShotFixtures.sparkline(for: holding, seed: index),
                previousClose: StoreShotFixtures.previousClose(of: holding)
            )
            items.append(item)
        }
        return items
    }
}

// MARK: - Network fixtures

/// Answers the Tracking and Updates reads with fixtures and swallows the writes they can
/// trigger. Registered on `URLSession.shared` (which `APIClient` uses) only while
/// `StoreScreenshotMode.isOn`; every other request passes through untouched.
nonisolated final class StoreShotURLProtocol: URLProtocol {
    private enum Route {
        case trackingFeed, portfolios, portfolioInsights, updatesTabs, portfolioWrite, swallowedWrite
        case updatesFeed(scope: String)
        case sentimentTrend(scope: String, days: Int)
    }

    private static func query(_ name: String, in url: URL) -> String? {
        let items: [URLQueryItem] = URLComponents(url: url, resolvingAgainstBaseURL: false)?.queryItems ?? []
        return items.first(where: { $0.name == name })?.value
    }

    private static func route(for request: URLRequest) -> Route? {
        guard StoreScreenshotMode.isOn, let url = request.url else { return nil }
        let path = url.path
        let method = (request.httpMethod ?? "GET").uppercased()
        if method == "GET" {
            if path.hasSuffix("/api/v1/tracking/assets") { return .trackingFeed }
            if path.hasSuffix("/api/v1/portfolios") { return .portfolios }
            if path.contains("/api/v1/portfolios/"), path.hasSuffix("/insights") { return .portfolioInsights }
            if path.hasSuffix("/api/v1/updates/tabs") { return .updatesTabs }
            if path.hasSuffix("/api/v1/updates/feed") {
                return .updatesFeed(scope: query("scope", in: url) ?? StoreShotFixtures.marketScope)
            }
            if path.hasSuffix("/api/v1/updates/sentiment-trend") {
                let scope: String = query("scope", in: url) ?? StoreShotFixtures.marketScope
                let days: Int = Int(query("days", in: url) ?? "") ?? 90
                return .sentimentTrend(scope: scope, days: days)
            }
            return nil
        }
        if path.contains("/api/v1/portfolios") { return .portfolioWrite }
        if path.contains("/api/v1/tracking/assets/holdings") || path.contains("/api/v1/watchlist") {
            return .swallowedWrite
        }
        return nil
    }

    override class func canInit(with request: URLRequest) -> Bool {
        route(for: request) != nil
    }

    override class func canonicalRequest(for request: URLRequest) -> URLRequest {
        request
    }

    override func startLoading() {
        guard let url = request.url, let route = Self.route(for: request) else {
            client?.urlProtocol(self, didFailWithError: URLError(.unsupportedURL))
            return
        }
        let body: Data
        switch route {
        case .trackingFeed: body = StoreShotFixtures.trackingFeedJSON()
        case .portfolios: body = StoreShotFixtures.portfoliosJSON()
        case .portfolioInsights: body = Data("null".utf8)
        case .updatesTabs: body = StoreShotFixtures.updatesTabsJSON()
        case .updatesFeed(let scope): body = StoreShotFixtures.updatesFeedJSON(scope: scope)
        case .sentimentTrend(let scope, let days):
            body = StoreShotFixtures.sentimentTrendJSON(scope: scope, days: days)
        case .portfolioWrite: body = StoreShotFixtures.portfolioJSON()
        case .swallowedWrite: body = Data("{}".utf8)
        }
        guard let response = HTTPURLResponse(
            url: url, statusCode: 200, httpVersion: "HTTP/1.1",
            headerFields: ["Content-Type": "application/json"]
        ) else {
            client?.urlProtocol(self, didFailWithError: URLError(.badServerResponse))
            return
        }
        client?.urlProtocol(self, didReceive: response, cacheStoragePolicy: .notAllowed)
        client?.urlProtocol(self, didLoad: body)
        client?.urlProtocolDidFinishLoading(self)
    }

    override func stopLoading() {}
}
#endif
