//
//  StoreScreenshotFixtures.swift
//  ios
//
//  DEBUG-ONLY sample data for `StoreScreenshotMode` (read that file's header first).
//
//  Every figure here is INVENTED. Prices, % moves and sparklines are sample values shown under
//  the "Sample data" label, never market data. Series are generated by a formula, not typed out,
//  so the file holds no large literal (a giant Swift literal crashed this Mac: CLAUDE.md,
//  Machine safety rule 7).
//
//  Wire fixtures are built with JSONSerialization in the shape the backend's response models
//  emit, so they travel through the app's real decoders and mappers:
//    GET  /api/v1/tracking/assets          → schemas/tracking.py      TrackingFeedResponse
//    GET  /api/v1/portfolios               → endpoints/portfolios.py  PortfolioListResponse
//    GET  /api/v1/portfolios/{id}/insights → null (a group with no holdings has no score)
//    GET  /api/v1/updates/tabs             → schemas/updates.py       UpdatesTabsResponse
//  Writes the Tracking tab can trigger (its feed-driven ticker purge PUTs the active group's
//  tickers) are answered here and never reach the server — against a real account they would
//  delete real rows.
//

#if DEBUG
import Foundation
import SwiftUI

/// One sample holding — the same five on Home's holdings strip, the Tracking list and the
/// Updates chips, so the screenshots agree with each other.
nonisolated struct StoreShotHolding: Sendable {
    let symbol: String
    let name: String
    let price: Double
    let changePercent: Double
    let marketCap: Double
    let sector: String
}

nonisolated enum StoreShotFixtures {
    static let portfolioId = "store-shot-sample"
    /// Shown as the group name on Tracking, Updates and Home — the label lives in the data too.
    static let groupName = "Sample data"

    static let holdings: [StoreShotHolding] = [
        StoreShotHolding(symbol: "AAPL", name: "Apple Inc.", price: 184.20, changePercent: 1.24,
                         marketCap: 2.84e12, sector: "Technology"),
        StoreShotHolding(symbol: "MSFT", name: "Microsoft Corporation", price: 412.50, changePercent: 0.86,
                         marketCap: 3.07e12, sector: "Technology"),
        StoreShotHolding(symbol: "NVDA", name: "NVIDIA Corporation", price: 131.80, changePercent: 2.41,
                         marketCap: 3.24e12, sector: "Technology"),
        StoreShotHolding(symbol: "AMZN", name: "Amazon.com, Inc.", price: 178.40, changePercent: -0.52,
                         marketCap: 1.87e12, sector: "Consumer Cyclical"),
        StoreShotHolding(symbol: "GOOGL", name: "Alphabet Inc.", price: 162.30, changePercent: 0.37,
                         marketCap: 2.01e12, sector: "Communication Services"),
    ]

    static func previousClose(of holding: StoreShotHolding) -> Double {
        holding.price / (1.0 + holding.changePercent / 100.0)
    }

    /// A smooth, deterministic intraday-shaped series from `start` to exactly `end`.
    static func series(seed: Int, count: Int, from start: Double, to end: Double) -> [Double] {
        var points: [Double] = []
        points.reserveCapacity(count)
        let span: Double = max(abs(end - start), start * 0.004)
        let phase: Double = Double(seed) * 1.7
        let last: Double = Double(max(count - 1, 1))
        for index in 0..<count {
            let t: Double = Double(index) / last
            let trend: Double = start + (end - start) * t
            let slow: Double = sin(t * 7.0 + phase) * 0.45
            let fast: Double = sin(t * 19.0 + phase * 2.3) * 0.2
            let taper: Double = 1.0 - t
            points.append(trend + (slow + fast) * span * taper)
        }
        return points
    }

    static func sparkline(for holding: StoreShotHolding, seed: Int) -> [Double] {
        series(seed: seed, count: 40, from: previousClose(of: holding), to: holding.price)
    }

    // MARK: Wire fixtures

    static func trackingFeedJSON() -> Data {
        var assets: [[String: Any]] = []
        for (index, holding) in holdings.enumerated() {
            var row: [String: Any] = [:]
            row["ticker"] = holding.symbol
            row["company_name"] = holding.name
            row["price"] = holding.price
            row["change_percent"] = holding.changePercent
            row["price_known"] = true
            row["change_known"] = true
            row["previous_close"] = previousClose(of: holding)
            row["sparkline_data"] = sparkline(for: holding, seed: index)
            row["spark_from"] = 0.0
            row["spark_to"] = 1.0
            row["logo_url"] = NSNull()
            row["sector"] = holding.sector
            row["country"] = "US"
            row["market_cap"] = holding.marketCap
            // No holding values: these are watchlist rows, so the holding fields are null.
            row["shares"] = NSNull()
            row["market_value"] = NSNull()
            row["asset_type"] = NSNull()
            assets.append(row)
        }
        let body: [String: Any] = ["assets": assets, "alerts": [Any]()]
        return json(body)
    }

    static func portfolioObject() -> [String: Any] {
        var items: [[String: Any]] = []
        for holding in holdings {
            items.append(["ticker": holding.symbol, "shares": NSNull(), "market_value": NSNull()])
        }
        var portfolio: [String: Any] = [:]
        portfolio["id"] = portfolioId
        portfolio["name"] = groupName
        portfolio["sort_order"] = 0
        portfolio["items"] = items
        portfolio["created_at"] = "2026-10-01T00:00:00Z"
        portfolio["updated_at"] = "2026-10-01T00:00:00Z"
        portfolio["is_active"] = true
        return portfolio
    }

    static func portfoliosJSON() -> Data {
        json(["portfolios": [portfolioObject()]])
    }

    /// The answer to any portfolio WRITE: the unchanged sample group (`PortfolioResponse`).
    static func portfolioJSON() -> Data {
        json(portfolioObject())
    }

    static func updatesTabsJSON() -> Data {
        var tabs: [[String: Any]] = []
        var market: [String: Any] = [:]
        market["scope"] = "__MARKET__"
        market["title"] = "Market"
        market["company_name"] = NSNull()
        market["change_percent"] = NSNull()
        market["logo_url"] = NSNull()
        market["is_market_tab"] = true
        market["is_locked"] = false
        market["asset_type"] = NSNull()
        tabs.append(market)
        for holding in holdings {
            var tab: [String: Any] = [:]
            tab["scope"] = holding.symbol
            tab["title"] = holding.symbol
            tab["company_name"] = holding.name
            tab["change_percent"] = holding.changePercent
            tab["logo_url"] = NSNull()
            tab["is_market_tab"] = false
            tab["is_locked"] = false
            tab["asset_type"] = "stock"
            tabs.append(tab)
        }
        var body: [String: Any] = [:]
        body["tabs"] = tabs
        body["group_name"] = groupName
        body["locked_count"] = 0
        body["tier_required"] = NSNull()
        return json(body)
    }

    private static func json(_ object: Any) -> Data {
        do {
            return try JSONSerialization.data(withJSONObject: object)
        } catch {
            print("📸 [StoreScreenshotMode] fixture encode failed: \(type(of: error)): \(error)")
            return Data("{}".utf8)
        }
    }
}

// MARK: - Home

/// Home in screenshot mode: the strip header reads "Sample data", every price, % move and
/// sparkline is INVENTED here (the previews' mock figures were not reused — some may once have
/// been copied from a live strip), the signals are LOCKED (a free account's shape — no invented
/// filings on real companies), and the holdings strip is the sample holdings.
final class StoreShotHomeRepository: HomeRepositoryProtocol {
    func fetchHomeDashboard() async throws -> HomeDashboardFetch {
        // No body: nothing is ever written to the on-device snapshot.
        HomeDashboardFetch(data: Self.dashboard, body: nil)
    }

    static var dashboard: HomeDashboardData {
        HomeDashboardData(
            marketStatusText: StoreShotFixtures.groupName,
            marketIsOpen: false,
            pulse: samplePulse,
            scanners: [moversCard, volumeCard, shortsCard],
            signals: MockHomeRepository.lockedSignals,
            themes: MockHomeRepository.themes,
            watchlist: holdingsStrip,
            watchlistTitle: StoreShotFixtures.groupName,
            watchlistIsGroup: true,
            trillionClub: MockHomeRepository.trillionClub
        )
    }

    // MARK: Market strip (invented values)

    private static var samplePulse: [MarketPulseItem] {
        var items: [MarketPulseItem] = []
        items.append(pulseItem("S&P 500 ETF", "SPY", .etf, price: 512.40, change: 0.48, seed: 11))
        items.append(pulseItem("Nasdaq ETF", "ONEQ", .etf, price: 68.20, change: 0.71, seed: 12))
        items.append(pulseItem("Dow Jones ETF", "DIA", .etf, price: 421.30, change: 0.22, seed: 13))
        items.append(pulseItem("Russell 2000 ETF", "IWM", .etf, price: 205.60, change: -0.35, seed: 14))
        items.append(pulseItem("Gold ETF", "GLD", .etf, price: 231.80, change: 0.15, seed: 15))
        items.append(pulseItem("Bitcoin", "BTCUSD", .crypto, price: 64_250.00, change: 1.10, seed: 16))
        return items
    }

    private static func pulseItem(
        _ name: String, _ symbol: String, _ type: MarketTickerType,
        price: Double, change: Double, seed: Int
    ) -> MarketPulseItem {
        let previous: Double = price / (1.0 + change / 100.0)
        let priceText: String = price >= 10_000
            ? price.formatted(.number.precision(.fractionLength(2)))
            : String(format: "%.2f", price)
        return MarketPulseItem(
            name: name, symbol: symbol, type: type,
            priceText: priceText, changeText: percentText(change), isPositive: change >= 0,
            spark: StoreShotFixtures.series(seed: seed, count: 30, from: previous, to: price),
            previousClose: previous
        )
    }

    private static func percentText(_ change: Double) -> String {
        (change >= 0 ? "+" : "") + String(format: "%.2f%%", change)
    }

    // MARK: Daily Scanners (invented values)

    private static func entry(
        _ rank: Int, _ symbol: String, _ name: String,
        _ primary: String, _ secondary: String, _ up: Bool
    ) -> ScannerEntry {
        ScannerEntry(rank: rank, symbol: symbol, name: name,
                     primaryText: primary, secondaryText: secondary, isPositive: up)
    }

    /// Rank 1 carries the card's sparkline.
    private static func head(_ entry: ScannerEntry, seed: Int, rising: Bool) -> ScannerEntry {
        var withSpark = entry
        let low: Double = 100
        let high: Double = 106
        withSpark.spark = StoreShotFixtures.series(seed: seed, count: 30, from: rising ? low : high, to: rising ? high : low)
        return withSpark
    }

    private static var moversCard: DailyScanner {
        var gainers: [ScannerEntry] = []
        gainers.append(head(entry(1, "AMD", "Advanced Micro", "+6.8%", "$162.40", true), seed: 21, rising: true))
        gainers.append(entry(2, "NFLX", "Netflix", "+5.2%", "$648.10", true))
        gainers.append(entry(3, "CRM", "Salesforce", "+4.6%", "$271.30", true))
        gainers.append(entry(4, "UBER", "Uber", "+4.1%", "$74.80", true))
        gainers.append(entry(5, "SHOP", "Shopify", "+3.7%", "$78.20", true))
        gainers.append(entry(6, "NVDA", "NVIDIA", "+2.4%", "$131.80", true))
        gainers.append(entry(7, "META", "Meta Platforms", "+2.2%", "$498.60", true))
        gainers.append(entry(8, "ADBE", "Adobe", "+1.9%", "$512.70", true))
        var losers: [ScannerEntry] = []
        losers.append(head(entry(1, "INTC", "Intel", "-5.4%", "$21.30", false), seed: 22, rising: false))
        losers.append(entry(2, "NKE", "Nike", "-4.2%", "$81.50", false))
        losers.append(entry(3, "DIS", "Disney", "-3.6%", "$92.40", false))
        losers.append(entry(4, "PYPL", "PayPal", "-3.1%", "$61.70", false))
        losers.append(entry(5, "F", "Ford Motor", "-2.7%", "$10.90", false))
        losers.append(entry(6, "BA", "Boeing", "-2.2%", "$171.20", false))
        losers.append(entry(7, "AMZN", "Amazon", "-0.5%", "$178.40", false))
        losers.append(entry(8, "KO", "Coca-Cola", "-0.4%", "$61.80", false))
        return DailyScanner(
            kind: .movers, title: "Today's Top Movers", subtitle: "",
            iconSystemName: "chart.line.uptrend.xyaxis", accent: AppColors.bullish,
            expandCTA: "See full leaderboard", gainers: gainers, losers: losers
        )
    }

    private static var volumeCard: DailyScanner {
        var rows: [ScannerEntry] = []
        rows.append(head(entry(1, "PLTR", "Palantir", "6.2×", "+3.4%", true), seed: 23, rising: true))
        rows.append(entry(2, "SOFI", "SoFi Tech", "4.8×", "+2.6%", true))
        rows.append(entry(3, "RIVN", "Rivian", "4.1×", "-1.9%", false))
        rows.append(entry(4, "HOOD", "Robinhood", "3.7×", "+4.2%", true))
        rows.append(entry(5, "LCID", "Lucid", "3.3×", "-2.8%", false))
        rows.append(entry(6, "MARA", "MARA Holdings", "3.0×", "+5.1%", true))
        rows.append(entry(7, "SNAP", "Snap", "2.8×", "-1.2%", false))
        rows.append(entry(8, "PLUG", "Plug Power", "2.6×", "+1.7%", true))
        return DailyScanner(
            kind: .volume, title: "Heavy Traffic", subtitle: "Unusual trading volume",
            iconSystemName: "chart.bar.fill", accent: AppColors.accentCyan, badgeText: "Volume",
            expandCTA: "See all unusual volume", entries: rows
        )
    }

    private static var shortsCard: DailyScanner {
        var rows: [ScannerEntry] = []
        rows.append(head(entry(1, "UPST", "Upstart", "21.7%", "$45.10", false), seed: 24, rising: false))
        rows.append(entry(2, "CVNA", "Carvana", "18.9%", "$132.40", false))
        rows.append(entry(3, "AI", "C3.ai", "17.6%", "$27.30", false))
        rows.append(entry(4, "LCID", "Lucid", "16.2%", "$3.10", false))
        rows.append(entry(5, "RIVN", "Rivian", "15.4%", "$12.60", false))
        rows.append(entry(6, "BYND", "Beyond Meat", "14.8%", "$6.40", false))
        rows.append(entry(7, "W", "Wayfair", "13.9%", "$48.20", false))
        rows.append(entry(8, "PTON", "Peloton", "12.7%", "$5.30", false))
        return DailyScanner(
            kind: .shorts, title: "Skeptical Money", subtitle: "Highest short interest",
            iconSystemName: "eye.fill", accent: AppColors.neutral, badgeText: "Shorts",
            expandCTA: "See all high short interest",
            infoNote: "High short interest reflects skepticism — and can fuel a short squeeze if the stock rallies.",
            entries: rows
        )
    }

    private static var holdingsStrip: [MarketPulseItem] {
        var items: [MarketPulseItem] = []
        for (index, holding) in StoreShotFixtures.holdings.enumerated() {
            let item = MarketPulseItem(
                name: holding.name,
                symbol: holding.symbol,
                type: .stock,
                priceText: String(format: "%.2f", holding.price),
                changeText: percentText(holding.changePercent),
                isPositive: holding.changePercent >= 0,
                spark: StoreShotFixtures.sparkline(for: holding, seed: index),
                previousClose: StoreShotFixtures.previousClose(of: holding)
            )
            items.append(item)
        }
        return items
    }
}

// MARK: - Network fixtures

/// Answers the Tracking and Updates-chip reads with fixtures and swallows the writes they can
/// trigger. Registered on `URLSession.shared` (which `APIClient` uses) only while
/// `StoreScreenshotMode.isOn`; every other request passes through untouched.
nonisolated final class StoreShotURLProtocol: URLProtocol {
    private enum Route {
        case trackingFeed, portfolios, portfolioInsights, updatesTabs, portfolioWrite, swallowedWrite
    }

    private static func route(for request: URLRequest) -> Route? {
        guard StoreScreenshotMode.isOn, let url = request.url else { return nil }
        let path = url.path
        let method = (request.httpMethod ?? "GET").uppercased()
        if method == "GET" {
            if path.hasSuffix("/api/v1/tracking/assets") { return .trackingFeed }
            if path.hasSuffix("/api/v1/portfolios") { return .portfolios }
            if path.contains("/api/v1/portfolios/"), path.hasSuffix("/insights") { return .portfolioInsights }
            if path.hasSuffix("/api/v1/updates/tabs") { return .updatesTabs }
            return nil
        }
        if path.contains("/api/v1/portfolios") { return .portfolioWrite }
        if path.contains("/api/v1/tracking/assets/holdings") || path.contains("/api/v1/watchlist") {
            return .swallowedWrite
        }
        return nil
    }

    override class func canInit(with request: URLRequest) -> Bool {
        route(for: request) != nil
    }

    override class func canonicalRequest(for request: URLRequest) -> URLRequest {
        request
    }

    override func startLoading() {
        guard let url = request.url, let route = Self.route(for: request) else {
            client?.urlProtocol(self, didFailWithError: URLError(.unsupportedURL))
            return
        }
        let body: Data
        switch route {
        case .trackingFeed: body = StoreShotFixtures.trackingFeedJSON()
        case .portfolios: body = StoreShotFixtures.portfoliosJSON()
        case .portfolioInsights: body = Data("null".utf8)
        case .updatesTabs: body = StoreShotFixtures.updatesTabsJSON()
        case .portfolioWrite: body = StoreShotFixtures.portfolioJSON()
        case .swallowedWrite: body = Data("{}".utf8)
        }
        guard let response = HTTPURLResponse(
            url: url, statusCode: 200, httpVersion: "HTTP/1.1",
            headerFields: ["Content-Type": "application/json"]
        ) else {
            client?.urlProtocol(self, didFailWithError: URLError(.badServerResponse))
            return
        }
        client?.urlProtocol(self, didReceive: response, cacheStoragePolicy: .notAllowed)
        client?.urlProtocol(self, didLoad: body)
        client?.urlProtocolDidFinishLoading(self)
    }

    override func stopLoading() {}
}
#endif
