//
//  FinancialInfoButton.swift
//  ios
//
//  Atom: Info button (i) for showing explanatory tooltips/sheets
//

import SwiftUI

struct FinancialInfoButton: View {
    let title: String
    let description: String
    @State private var showInfo = false

    var body: some View {
        Button {
            showInfo = true
        } label: {
            Image(systemName: "info.circle")
                .font(.system(size: 14))
                .foregroundColor(AppColors.textMuted)
        }
        .buttonStyle(PlainButtonStyle())
        .sheet(isPresented: $showInfo) {
            FinancialInfoSheet(title: title, description: description)
                .presentationDetents([.medium])
                .presentationDragIndicator(.visible)
        }
    }
}

// MARK: - Info Sheet
struct FinancialInfoSheet: View {
    let title: String
    let description: String
    @Environment(\.dismiss) private var dismiss

    var body: some View {
        NavigationView {
            ZStack {
                AppColors.background
                    .ignoresSafeArea()

                ScrollView {
                    VStack(alignment: .leading, spacing: AppSpacing.lg) {
                        Text(description)
                            .font(AppTypography.body)
                            .foregroundColor(AppColors.textSecondary)
                            .lineSpacing(4)
                    }
                    .padding(AppSpacing.lg)
                }
            }
            .navigationTitle(title)
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .navigationBarTrailing) {
                    Button("Done") {
                        dismiss()
                    }
                    .foregroundColor(AppColors.primaryBlue)
                }
            }
        }
        .preferredColorScheme(.dark)
    }
}

// MARK: - Info Descriptions
enum FinancialInfoContent {
    static let earnings = """
    Earnings shows the company's quarterly Earnings Per Share (EPS) compared to analyst estimates.

    • Surprised: The percentage by which actual earnings beat or missed estimates
    • Beat: When actual EPS exceeds the estimate
    • Missed: When actual EPS falls below the estimate
    • Price Toggle: Shows the stock price at each earnings release

    Higher beat rates and positive surprises typically indicate strong company performance.
    """

    static let growth = """
    Growth metrics show how key financial figures have changed year-over-year.

    • Revenue: Total sales generated by the company
    • EPS: Earnings Per Share - profit allocated to each share
    • Net Income: Total profit after all expenses
    • Operating Profit: Profit from core business operations
    • Free Cash Flow: Cash available after capital expenditures

    Consistent growth indicates a healthy, expanding business.
    """

    static let revenueBreakdown = """
    This section shows how the company generates revenue and manages costs.

    Revenue Sources: Breakdown of income by product/service category
    Cost Structure:
    • Cost of Sales: Direct costs to produce goods/services
    • Operating Expenses: Overhead costs (R&D, marketing, admin)
    • Tax: Income tax expense
    • Net Profit: What remains after all costs

    A diversified revenue base and high profit margins indicate business strength.
    """

    static let profitPower = """
    Profit margins measure how efficiently the company converts revenue into profit.

    • Gross Margin: Revenue minus cost of goods sold
    • Operating Margin: Profit from operations before interest and taxes
    • FCF Margin: Free cash flow as a percentage of revenue
    • Net Margin: Final profit as a percentage of revenue

    Higher margins indicate better pricing power and cost control. Compare to sector averages for context.
    """

    static let healthCheck = """
    Health Check evaluates the company's financial strength across key metrics.

    • Debt-to-Equity: Lower values indicate less financial risk
    • P/E Ratio: Price relative to earnings - helps assess valuation
    • Return on Equity: How efficiently the company uses shareholder capital
    • Current Ratio: Ability to pay short-term obligations

    Green indicates strength, yellow is neutral, and red suggests caution.
    """

    static let signalOfConfidence = """
    Signal of Confidence shows how the company returns capital to shareholders.

    • Dividends: Cash payments to shareholders, shown as yield %
    • Buybacks: Share repurchases that increase ownership value
    • Shares Outstanding: Total shares - decreasing is positive for shareholders

    High total yield (dividends + buybacks) indicates management confidence in the business and commitment to shareholders.
    """
}

// MARK: - Preview
#Preview {
    ZStack {
        AppColors.background
            .ignoresSafeArea()

        HStack {
            Text("Earnings")
                .font(AppTypography.headline)
                .foregroundColor(AppColors.textPrimary)

            FinancialInfoButton(
                title: "Earnings",
                description: FinancialInfoContent.earnings
            )
        }
    }
}
